[#957] Login on resuming form
open-formulieren/open-forms pull request #1021
Opened 2021-12-02 16:18 UTC by SilviaAmAm

Part of #957

2021-12-02 16:47 UTC, sergei-maertens requested changes
Can we also rename the `test_endpoints` module to something with a proper meaningful name?

2021-12-02 16:47 UTC, sergei-maertens commented on src/openforms/authentication/contrib/demo/plugin.py
> +        request.session["form_auth"] = {
session key is defined as a constant in https://github.com/open-formulieren/open-forms/blob/master/src/openforms/authentication/constants.py#L5

2021-12-02 16:47 UTC, sergei-maertens commented on src/openforms/authentication/contrib/demo/tests/test_plugin.py
> +        self.assertNotIn("form_auth", self.client.session)
please use the constant

2021-12-02 16:47 UTC, sergei-maertens commented on src/openforms/authentication/contrib/demo/tests/test_plugin.py
> +        self.assertIn("form_auth", self.client.session)
please use the constant

2021-12-02 16:47 UTC, sergei-maertens commented on src/openforms/authentication/contrib/demo/tests/test_plugin.py
> +        self.assertEqual("bsn", self.client.session["form_auth"]["attribute"])
please use `AuthAttribute.bsn` from the constants

2021-12-02 16:47 UTC, sergei-maertens commented on src/openforms/authentication/contrib/eherkenning/views.py
> +from ...contrib.digid.mixins import AssertionConsumerServiceMixin
```suggestion
from ..digid.mixins import AssertionConsumerServiceMixin
```
?

2021-12-02 16:47 UTC, sergei-maertens commented on src/openforms/submissions/tests/test_endpoints.py
> +        )
think you can shortcut this a lot with either `SubmissionFactory.create(form__generate_minimal_setup=True, form__formstep__form_definition__login_required=True)` or `SubmissionFactory.from_components(...)`

2021-12-02 16:47 UTC, sergei-maertens commented on src/openforms/submissions/tests/test_endpoints.py
> +        self.assertNotIn("form-submissions", self.client.session)
please use the constant defined for this session key

2021-12-02 16:47 UTC, sergei-maertens commented on src/openforms/submissions/views.py
> +        if "form_auth" in self.request.session:
please use the constant

2021-12-03 08:38 UTC, SilviaAmAm commented on src/openforms/authentication/contrib/eherkenning/views.py
> +from ...contrib.digid.mixins import AssertionConsumerServiceMixin
No idea what happened here :sweat_smile:

2021-12-03 11:23 UTC, sergei-maertens approved these changes

2021-12-03 11:23 UTC, sergei-maertens commented on src/openforms/submissions/tests/test_resume_form_view.py
> +        session["form_auth"] = {
Use constant

2021-12-03 11:23 UTC, sergei-maertens commented on src/openforms/submissions/tests/test_resume_form_view.py
> +        session["form_auth"] = {
Use constant

2021-12-03 11:23 UTC, sergei-maertens commented on src/openforms/submissions/tests/test_resume_form_view.py
> +        session["form_auth"] = {
Use constant

2021-12-03 11:23 UTC, sergei-maertens commented on src/openforms/submissions/tests/test_resume_form_view.py
> +        session["form_auth"] = {
Use constant

2021-12-03 11:43 UTC, merged