[#990] Added regression test for multivalue field breaking PDF report
open-formulieren/open-forms pull request #1058
Opened 2021-12-10 13:15 UTC by Bartvaderkin

2021-12-10 15:07 UTC, Bartvaderkin commented
This is a big mess and really needs #1059

I did the quickfix that keeps the current situation and output: for example these values are not localized.

2021-12-10 16:12 UTC, sergei-maertens requested changes

2021-12-10 16:12 UTC, sergei-maertens commented on src/openforms/submissions/tests/factories.py
> +        with_report=True,
would be better suited as a trait:

```py
with_report = factory.Trait(
    report=factory.SubFactory(SubmissionReportFactory, submission=factory.SelfAttribute(".."))
)
```

not sure if this exact invocation of `SelfAttribute` works, but it should be something like that. See docs: https://factoryboy.readthedocs.io/en/stable/recipes.html#copying-fields-to-a-subfactory

2021-12-13 07:32 UTC, sergei-maertens approved these changes

2021-12-13 07:32 UTC, sergei-maertens commented
:adhesive_bandage:

2021-12-13 07:41 UTC, merged