NLX integration
open-formulieren/open-forms pull request #1091
Opened 2021-12-17 10:46 UTC by sergei-maertens

2021-12-17 19:04 UTC, joeribekker requested changes
The obtain certs script and main.py seem nice but are never mentioned in the docs? I don't see them called automatically so a small mention when or why to use them seems appropriate in the docs.

2021-12-17 19:04 UTC, joeribekker commented on nlx/obtain-certs.sh
> +COMMON_NAME=inway.open-forms.test.maykin.opengem.nl
Another real URL

2021-12-17 19:46 UTC, sergei-maertens commented on nlx/.env
> +INWAY_SELF_ADDRESS=inway.open-forms.test.maykin.opengem.nl
it also doesn't exist yet, need to come up with a proper way for this, otherwise the stack doesn't properly boot up :(

2021-12-20 10:30 UTC, joeribekker approved these changes
Approved and checked. It works :)

Added 2 small directory hints.

2021-12-20 10:30 UTC, joeribekker commented on nlx/README.md
> +as possible:
```suggestion
The included certificates are expired, at the time of writing. Please go to the 
`nlx-try-me` folder and follow the docs in 
[`nlx-try-me/pki/README.md`](./nlx-try-me/pki/README.md) to re-generate the intermediate
and host certificate. Note that you need to install the `cfssl` tooling if you don't 
have it yet.

Finally, go back to the `nlx` folder and generate your own local certificates. Follow
the directions presented by the script:
```

2021-12-20 10:30 UTC, joeribekker commented on nlx/README.md
> +Navigate to this directory and start the components using docker-compose:
```suggestion
Navigate to this (`nlx`) directory and start the components using docker-compose:
```

2021-12-20 11:44 UTC, merged