Camunda process selection + registration backend core
open-formulieren/open-forms pull request #1102
Opened 2021-12-21 11:56 UTC by sergei-maertens

2021-12-21 17:18 UTC, sergei-maertens commented
@SilviaAmAm - I would appreciate a frontend-code review!

2021-12-22 16:16 UTC, SilviaAmAm requested changes

2021-12-22 16:16 UTC, SilviaAmAm commented on src/openforms/js/components/admin/form_design/registrations/camunda.js
> +                required
The `processDefinition` is missing the help text (`rawDescription` field in the `processDefinitionVersion`)

2021-12-22 16:48 UTC, sergei-maertens commented on src/openforms/js/components/admin/form_design/registrations/camunda.js
> +        }, [PROCESS_DEFINITIONS_ENDPOINT]
it's not, but this ensures that the hook only runs once. I should use `[]` instead though, that has the same impact.

2021-12-22 16:49 UTC, sergei-maertens commented on src/openforms/js/components/admin/form_design/RegistrationFields.js
> +const BackendType = PropTypes.shape({
good suggestion, won't pollute this PR with that cleanup though. It also makes things a bit worse - it helps to keep the type defs in sync, but seeing the shape of data entering the component now requires you to open another file.

2021-12-22 17:49 UTC, joeribekker approved these changes
Looks good but please commit my translations :)

2021-12-22 17:49 UTC, joeribekker commented on src/openforms/js/lang/nl.json
> +    "defaultMessage": "The process definition for which to start a process instance.",
Make my life easier by not having to search for untranslated texts...

```suggestion
    "defaultMessage": "De procesdefinitie waarvoor een proces instantie gestart moet worden.",
```

2021-12-22 17:49 UTC, joeribekker commented on src/openforms/js/lang/nl.json
> +    "defaultMessage": "Which version of the process definition to start. The latest version is used if not specified.",
```suggestion
    "defaultMessage": "Welke versie van de procesdefinitie moet gebruikt worden. Indien niet opgegeven dan wordt altijd de laatste versie gebruikt.",
```

2021-12-22 17:49 UTC, joeribekker commented on src/openforms/js/lang/nl.json
> +    "defaultMessage": "Process",
```suggestion
    "defaultMessage": "Proces",
```

2021-12-22 17:49 UTC, joeribekker commented on src/openforms/js/lang/nl.json
> +    "defaultMessage": "Version",
```suggestion
    "defaultMessage": "Versie",
```

2021-12-23 08:53 UTC, merged