[#1000] Implemented and applied custom permission for FormAPI viewsets
open-formulieren/open-forms pull request #1137
Opened 2021-12-30 13:12 UTC by Bartvaderkin

Closes #1000

2021-12-31 12:08 UTC, sergei-maertens requested changes

2021-12-31 14:50 UTC, Bartvaderkin commented on src/openforms/forms/tests/test_api_form_versions.py
> +        user.user_permissions.add(Permission.objects.get(codename="change_form"))
I need a `post_generation` decorator+method in the factory to create the user_permissions many2many to Permission, but factoryboy doesn't call it when set it from a trait.

But just the post_generation should clear things up a bit anyway:

````
user = StaffUserFactory.create(
    user_permissions=["change_form"],
)
````

2021-12-31 15:04 UTC, Bartvaderkin commented on src/openforms/forms/tests/test_api_form_versions.py
> +        user.user_permissions.add(Permission.objects.get(codename="change_form"))
Well.. it would cleanup more if many tests didn't re-use their user so we still need the boilerplate.

2021-12-31 15:48 UTC, sergei-maertens commented on src/openforms/forms/tests/test_api_form_versions.py
> +        user.user_permissions.add(Permission.objects.get(codename="change_form"))
you can define the trait along the ways of:

```py
some_trait = factory.Trait(
    change_permission=factory.PostGeneration(...),
)
```

which is essentially equivalent to a method with `@factory.post_generation` but it's only called when the trait is True. Check `FormFactory.Params.generate_minimal_setup` for a similar example :)

2022-01-03 16:07 UTC, sergei-maertens approved these changes
Good enough for now, though I think we'll go the Trait route at some point in the future.

2022-01-03 16:07 UTC, merged