Feature/1007 iotype per filefield
open-formulieren/open-forms pull request #1164
Opened 2022-01-07 11:48 UTC by stevenbal

Fixes: #1007

TODO:
- [ ] Dynamic form

2022-01-07 15:00 UTC, stevenbal commented
To start, I added the catalogus.domein to the labels (so you can at least see to which catalogus the informatieobjecttype belongs to). I was looking into using optgroups, but it seems like the FormIO implementation of `select` doesn't support this?

![Screenshot from 2022-01-07 15-56-20](https://user-images.githubusercontent.com/29249171/148562157-2cfbbef4-3cf8-4037-8424-87cc4d51ae5d.png)

2022-01-10 11:44 UTC, stevenbal commented
I guess to allow `optgroups`, we would have to override the template for `select`? I'm not sure how to do this though

2022-01-11 11:29 UTC, sergei-maertens commented
@stevenbal right, it looks like Formio does not support that out of the box looking at https://github.com/formio/formio.js/blob/4.12.x/src/templates/bootstrap/selectOption/form.ejs :(

Might be an option to define a custom `Select` component subclass, which can render a custom `SelectOption` template. Feel free to work on this, but I probably won't be able to review this/follow up until after the demo coming Monday.

2022-01-11 14:25 UTC, stevenbal commented
> edit: did a quick check, and choices.js (used by Formio for selects) does support optgroup, so maybe with some configuration it might be possible to beat it into submission.

I tried to see if I could somehow get this to work, but I don't know where I would change this. I thought I would be able to override `templates/selectOption.js`, but `select.js` doesn't seem to use this template.

I guess I'll leave this out for now?

2022-01-11 16:12 UTC, sergei-maertens commented
Let's park it for now, since I don't have bandwith at the moment to help with this.

2022-05-16 09:56 UTC, stevenbal commented
I got optgroups working, the only thing is that they do not show up when performing search
![cbzxFxtJ4h](https://user-images.githubusercontent.com/29249171/168567167-d07412d7-4352-425a-b4c4-2a536c8572b3.gif)

2022-05-16 10:23 UTC, sergei-maertens commented
@stevenbal the black highlight was fixed last friday! :)

2022-05-16 12:08 UTC, stevenbal commented
> for the optgroups - if the behaviour is consistent with https://formio.github.io/formio.js/app/builder, then it is what it is

By default formio doesn't seem to support optgroups (from what I see), but search works the same as in the builder demo

2022-05-19 11:01 UTC, sergei-maertens requested changes

2022-05-19 11:01 UTC, sergei-maertens commented on src/openforms/registrations/contrib/zgw_apis/service.py
> +) -> str:
The function name is confusing, the `retrieve` implies to me that an HTTP call is made, but that's not the case.

Wouldn't it make more sense to make this a method on the `SubmissionFileAttachment` too? It basically should only interface with `openforms.formio.service` and internal data structures.

2022-05-30 10:55 UTC, stevenbal commented on src/openforms/registrations/api/views.py
> +        return iotypen
Hmm, I tried an approach like this to fetch the IOtypen in parallel:

```python
def get_objects(self):
        ...

        catalogus_data = get_paginated_results(client, "catalogus")
        catalogus_mapping = {
            catalogus["url"]: factory(Catalogus, catalogus)
            for catalogus in catalogus_data
        }

        def get_iotypen(catalogus: str) -> List[dict]:
            iotypen_data = get_paginated_results(
                client, "informatieobjecttype", query_params={"catalogus": catalogus}
            )
            iotypen = [
                {
                    "informatieobjecttype": factory(InformatieObjectType, iotype),
                    "catalogus": catalogus_mapping[iotype["catalogus"]],
                }
                for iotype in iotypen_data
            ]
            return iotypen

        with parallel() as executor:
            _data = executor.map(get_iotypen, list(catalogus_mapping.keys()))

        iotypen = sum(list(_data), [])
        return iotypen
```

But this actually seemed to slow things down slightly, is it worth it here to fetch stuff in parallel :thinking:?
![Screenshot from 2022-05-30 12-46-00](https://user-images.githubusercontent.com/29249171/170977874-b2340ba7-9bc6-467e-95e4-4354b1578cb3.png)

![Screenshot from 2022-05-30 12-46-18](https://user-images.githubusercontent.com/29249171/170977907-1f0a4c80-fecd-4430-a25f-02ec918f8668.png)

2022-05-30 14:11 UTC, sergei-maertens commented on src/openforms/registrations/api/views.py
> +        return iotypen
Numbers don't lie - current case is probably the more efficient one then. Probably it'll only start making a difference if there are many large catalogi (involving pagination and multiple sequential calls), as long as it all fits in a single call you don't have the HTTP overhead. So okay to leave it as is now, thanks for profiling it!

2022-05-30 15:48 UTC, sergei-maertens approved these changes

2022-05-30 15:48 UTC, merged