Versioning setup + prepare 1.0.0-rc.0 version
open-formulieren/open-forms pull request #1200
Opened 2022-01-17 11:17 UTC by sergei-maertens

Gotta do the same for the SDK too :)

2022-01-17 11:19 UTC, sergei-maertens commented on .bumpversion.cfg
> +	{major}.{minor}.{patch}
There are some limitations with this, but I wasn't immediately able to reproduce that in my local env. See https://github.com/c4urself/bump2version/issues/190

2022-01-17 17:47 UTC, joeribekker requested changes

2022-01-17 17:47 UTC, joeribekker commented on docs/developers/sdk/embedding.rst
> +The SDK follow semantic versioning.
```suggestion
The SDK follows semantic versioning.
```

And link to semver

2022-01-26 11:22 UTC, joeribekker approved these changes

2022-01-26 12:02 UTC, merged