[#1272] Hardened XML submission export to handle multi-value fields
open-formulieren/open-forms pull request #1283
Opened 2022-02-02 10:42 UTC by Bartvaderkin

Fixes #1272

2022-02-04 11:14 UTC, Bartvaderkin commented
I think the export value formatting should maybe also go through the formatters app, since its field type dependent formatting/serialising.

2022-02-04 11:43 UTC, sergei-maertens commented
> I think the export value formatting should maybe also go through the formatters app, since its field type dependent formatting/serializing but that's maybe for another time.

Agree - and it would tie in with the Camunda registration backend which also requires Formio components to be converted into python types: https://github.com/open-formulieren/open-forms/blob/master/src/openforms/registrations/contrib/camunda/type_mapping.py

All this kind of functionality really belongs in the `openforms.formio` package.

2022-02-04 12:11 UTC, sergei-maertens requested changes

2022-02-04 12:11 UTC, sergei-maertens commented on src/openforms/submissions/exports.py
> +        return json.dumps(value)
I don't like that suddenly we have JSON inside of XML and require XML parsers to also parse JSON.

For an export with singular values, we now get this:

```xml
<submissions>
  <submission>
    <field name="Formuliernaam">Camunda demo sprint 11</field>
    <field name="Inzendingdatum">2022-01-17T15:18:02.140744</field>
    <field name="bedrag">500</field>
    <field name="invoiceCategory">Misc</field>
  </submission>
</submissions>
```

which is okay. But the multiple variant would result in:

```xml
<submissions>
  <submission>
    <field name="Formuliernaam">Camunda demo sprint 11</field>
    <field name="Inzendingdatum">2022-01-17T15:18:02.140744</field>
    <field name="bedrag">[500, 600]</field>
    <field name="invoiceCategory">["Misc", "Staff"]</field>
  </submission>
</submissions>
```

how does a parser determine what to parse as JSON and what to parse as string?

I'd much prefer the following output which sticks to XML semantics:

```xml
<submissions>
  <submission>
    <field name="Formuliernaam"><value>Camunda demo sprint 11</value></field>
    <field name="Inzendingdatum"><value>2022-01-17T15:18:02.140744</value></field>
    <field name="bedrag">
        <value>500</value>
        <value>600</value>
    </field>
    <field name="invoiceCategory">
        <value>Misc</value>
        <value>Staff</value>
    </field>
  </submission>
</submissions>
```

* this normalizes that `field` has at least one `value` element
* this opens up the path to add type information in the future / multi information: e.g. `<field name="bedrag" type="int" multiple="true">`

2022-02-08 17:57 UTC, sergei-maertens commented on src/openforms/submissions/exports.py
> +import json
```suggestion
```

2022-02-08 17:57 UTC, sergei-maertens approved these changes

2022-02-08 18:11 UTC, merged