[#1254] Rework Column component
open-formulieren/open-forms pull request #1327
Opened 2022-02-10 16:08 UTC by SilviaAmAm

Fixes #1254 

Front end: https://github.com/open-formulieren/open-forms-sdk/pull/163

2022-02-11 15:51 UTC, SilviaAmAm commented
Current look of it:

Editor:
![Screenshot from 2022-02-11 16-47-28](https://user-images.githubusercontent.com/19154114/153623450-c4869647-cb91-4f42-9fb5-a7691b9f46d5.png)

SDK:
![Screenshot from 2022-02-11 16-47-38](https://user-images.githubusercontent.com/19154114/153623449-9d9acb92-988c-49f1-99f7-914d8d898d46.png)

2022-02-11 21:30 UTC, sergei-maertens requested changes

2022-02-11 21:30 UTC, sergei-maertens commented on src/openforms/js/components/formio_builder/templates/columns.ejs
> +        <div class="col--span-{{column.size}}" ref="{{ctx.columnKey}}">
```suggestion
        <div class="col col--span-{{column.size}}" ref="{{ctx.columnKey}}">
```
proper BEM class naming :-)

2022-02-11 21:30 UTC, sergei-maertens commented on src/openforms/scss/components/builder/_columns.scss
> +    }
https://sass-lang.com/documentation/at-rules/control/each :-)

2022-02-16 13:09 UTC, SilviaAmAm commented on src/openforms/scss/components/builder/_columns.scss
> +    }
Amazing :scream:

2022-02-16 14:10 UTC, sergei-maertens approved these changes

2022-02-16 14:10 UTC, sergei-maertens commented
Waiting for SDK to be approved before we merge this :)

2022-02-16 15:14 UTC, merged