[#1621] Added Ctrl+S keyboard shortcut to Save & Continue to form changeform
open-formulieren/open-forms pull request #1623
Opened 2022-05-17 13:38 UTC by Bartvaderkin

2022-05-17 15:42 UTC, sergei-maertens requested changes
Inline scripts are to be avoid, especially if/when we enable CSP in the admin.

Please move this to a new JS module somewhere in https://github.com/open-formulieren/open-forms/tree/master/src/openforms/js/components/admin and ensure it is imported/loaded in https://github.com/open-formulieren/open-forms/blob/master/src/openforms/js/components/admin/index.js

2022-05-19 09:19 UTC, Bartvaderkin commented
I replaced the template based solution with the suggestion.

2022-05-19 09:26 UTC, sergei-maertens requested changes
As discussed this morning, a "shortcuts" entry in the documentation is still missing.

2022-05-19 09:26 UTC, sergei-maertens commented on src/openforms/js/components/admin/Keyboard.js
> +            if (event.ctrlKey && event.key === 's') {
I think this doesn't capture command key on Mac, see https://stackoverflow.com/a/3922353 - I think you also want to check `event.metaKey`

2022-05-19 09:28 UTC, sergei-maertens commented on src/openforms/js/components/admin/Keyboard.js
> +        document.addEventListener('keydown', event => {
I'm also wondering if we shouldn't tap into `keyup` rather than `keydown`? That triggers the save when the keys are released.

2022-05-19 09:29 UTC, sergei-maertens commented on src/openforms/js/components/admin/Keyboard.js
> +        document.addEventListener('keydown', event => {
I'm also wondering if we shouldn't tap into `keyup` rather than `keydown`? That triggers the save when the keys are released.

2022-05-19 09:49 UTC, sergei-maertens requested changes

2022-05-19 09:49 UTC, sergei-maertens commented on docs/manual/forms/shortcuts.rst
> +.. shortcuts:
```suggestion
.. _manual_forms_shortcuts:
```

2022-05-19 11:06 UTC, sergei-maertens approved these changes
Shiny

2022-05-19 11:43 UTC, merged