Fix logo sizing for PDFs — [#1715]
open-formulieren/open-forms pull request #1728
Opened 2022-06-28 15:39 UTC by dariomory

Fixes #1715

### Example output

Input image:

> JPEG image data, JFIF standard 1.02, resolution (DPI), density 72x72, segment length 16, Exif Standard: [TIFF image data, big-endian, direntries=5, xresolution=206, yresolution=214, resolutionunit=2], baseline, precision 8, 4000x4000, components 3

![pdf_output](https://user-images.githubusercontent.com/58147939/176221514-11ab482c-9771-4110-bd8f-4f794338c8ed.png)

2022-06-29 07:00 UTC, sergei-maertens requested changes
Why is the logo centered while the webpages aligns it in the top-left?

2022-06-29 09:50 UTC, dariomory commented on src/openforms/scss/pdfs/_header.scss
> -
Hmm.. got it. I assumed this behavior was desired according to [your note](https://github.com/open-formulieren/open-forms/issues/1715#issuecomment-1167081081):

> PDFs with/without logo/header -> vertical spacing should remain consistent

2022-06-30 09:25 UTC, sergei-maertens commented
> > Why is the logo centered while the webpages aligns it in the top-left?
> 
> Good question, looking into it. Note that I expected the logo to be centered for the pdf, otherwise I would remove the following line:
> 
> https://github.com/open-formulieren/open-forms/blob/62f2d197e4319beb3dc3c46a82ecf6a897ac8b15/src/openforms/scss/pdfs/_header.scss#L32

Please fix this so that the logo is left-aligned like on the website itself.

2022-07-05 09:15 UTC, sergei-maertens approved these changes

2022-07-05 09:15 UTC, merged