Stuf ZDS integration creates hardcoded document
open-formulieren/open-forms pull request #1770
Opened 2022-07-12 10:18 UTC by dariomory

Fixes #1769

2022-07-12 14:01 UTC, sergei-maertens requested changes
Your test assertions have lowercased values, while the situation before this patch had uppercase values. How did you confirm that lowercase values are correct?

2022-07-12 14:40 UTC, dariomory commented on src/openforms/registrations/contrib/stuf_zds/plugin.py
> +        default=VertrouwelijkheidsAanduidingen.vertrouwelijk,
Suggested by @alextreme. See https://github.com/open-formulieren/open-forms/issues/1769#issue-1301718751

2022-07-14 09:19 UTC, sergei-maertens approved these changes
Tweaked the tests to ensure we can properly upgrade without breaking existing forms (and made them pass too).

2022-07-14 09:41 UTC, merged

2022-07-14 09:50 UTC, sergei-maertens commented
Backports `stable/1.0.x`: c981cbe83245c392261814e8776c739a639be93b, 28e8761fd17d711f0365790f30eeb17a2a95a99e and 932fbd28177b391deff9d008b980f92ec53e97e0

Backports `stable/1.1.x`: f461c13ad5ca70b2b01a747a987765894a20255f, b9520f3db46e062aa3011f111ea452961f5d7f59 and 387315bebace1b1e836bef12aee831d40827ec85