[#1792] Display validation errors for variables
open-formulieren/open-forms pull request #1800
Opened 2022-07-21 12:55 UTC by SilviaAmAm

Fixes #1792

2022-07-21 14:31 UTC, SilviaAmAm commented
![Screenshot from 2022-07-21 16-29-48](https://user-images.githubusercontent.com/19154114/180239788-ec002640-e4a6-4f43-ba22-f579a6e4a66d.png)

2022-07-21 16:12 UTC, sergei-maertens requested changes

2022-07-21 16:12 UTC, sergei-maertens commented on src/openforms/js/components/admin/form_design/Tab.js
> +import FAIcon from '../FAIcon';
```suggestion
import FAIcon from 'components/admin//FAIcon';
```
& we can group the imports a bit nicer (3rd party / absolute imports / relative imports)

2022-07-21 16:12 UTC, sergei-maertens commented on src/openforms/js/components/admin/form_design/form-creation-form.js
> +        });
with immer it's more natural to mutate in place on the draft - something like:

```js
variablesValidationErrors.forEach((errors, index) => {
  draft.formVariables[index].errors = errors;
});
```

2022-07-21 16:12 UTC, sergei-maertens commented on src/openforms/js/components/admin/form_design/variables/VariablesTable.js
> +            noVTextField={true}
```suggestion
            noVTextField
```
this is equivalent for boolean props

2022-07-22 08:00 UTC, sergei-maertens approved these changes

2022-07-22 08:05 UTC, merged