[#1760] Variables creation validation
open-formulieren/open-forms pull request #1820
Opened 2022-07-28 09:54 UTC by SilviaAmAm

**Changes**
Backend validation to check that all component variables have a corresponding field in the configuration.

2022-07-28 14:03 UTC, sergei-maertens approved these changes
Couple cleanups, shouldn't be too bad.

I am re-thinking the first task though and the remark of having to look up things - in the serializer we need to look up the component anyway to validate it. Couldn't we override the `save` method of `FormVariable` and derive the default value from there? Something like:

```py
    def save(self, *args, **kwargs):
        self._derive_initial_value()
        super().save(*args, **kwargs)

    def _derive_initial_value(self):
        if self.source != FormVariableSources.compnent:
            return
        if not (fd := self.form_definition):
            return

        if self.initial_value:
            return

        component = get_component(fd.configuration, self.key)
        self.initial_value = component.get("defaultValue", None)
```

performance wise this shouldn't be a big problem, because the serializer sets `variable.form_definition`, so there's no lookup there. And we remain within the context of our `form_definition`, so there's no traversal of relations, right?

2022-07-29 13:22 UTC, SilviaAmAm commented
I updated it so that now the backend sets both the `initial_value` and the `data_type` for component variables.
I am not entirely sure what to do in the front end: if we remove the current code, you would only see the `initial_value` and `data_type` populated after saving the form :thinking:

2022-08-04 09:37 UTC, sergei-maertens requested changes

2022-08-04 09:37 UTC, sergei-maertens commented on src/openforms/formio/utils.py
> +from ..forms.constants import FormVariableDataTypes
```suggestion
from openforms.forms.constants import FormVariableDataTypes
```

2022-08-04 09:37 UTC, sergei-maertens commented on src/openforms/forms/api/serializers/form_variable.py
> +from openforms.submissions.form_logic import get_component
probably better to move `get_component` to `openforms.formio.utils`

2022-08-08 07:53 UTC, sergei-maertens approved these changes

2022-08-08 07:53 UTC, merged