Added more registration fields
open-formulieren/open-forms pull request #2025
Opened 2022-09-12 13:24 UTC by joeribekker

2022-09-14 12:44 UTC, joeribekker reviewed
@dariomory I see you removed the `kvk` attribute from the ZGW test: https://github.com/open-formulieren/open-forms/pull/2025/commits/82f2288e63dae3ce34f795e15a8b83abd4eebcff#diff-857464e519bdf16c980dc00fc37c7db08396ba2b86225132f7d5542ae6671621R407-L383

It is however present in the StUF-ZDS version of the test, so I'd like to keep them the same.

Can we make the KvK a different number from the Vestigingsnummer? There is some logic that says "if there is a Vestigingsnummer" it overrides the KvK field

So please change those tests, and add 1 more (sub)test that only sends the kvk-number (so no vestigingsnummer, but the kvk number should be shown in the vestigingsnumber field in SOAP and REST

2022-09-15 12:14 UTC, sergei-maertens requested changes
I think the newly added tests are doing too much and aren't focused on just the extra StUF-ZDS/ZGW attributes, but since they're passing I'll let it slide.

2022-09-15 12:14 UTC, sergei-maertens commented on src/openforms/registrations/contrib/zgw_apis/tests/test_backend.py
> +                },
(in the future) this could be a preset field maybe

2022-09-15 12:14 UTC, sergei-maertens commented on src/openforms/registrations/contrib/zgw_apis/plugin.py
> +            )
I think this doesn't catch the case where the field has an empty string for value - then there will not be a fallback to `kvk`.

2022-09-15 12:14 UTC, sergei-maertens commented on src/openforms/registrations/contrib/zgw_apis/tests/test_backend.py
> +    def test_submission_with_zgw_backend_with_vestiging_initiator_kvk_only(self, m):
I'm missing a test case where an optional `vestigingsNummer` field is present with an empty string as value.

2022-09-15 12:14 UTC, sergei-maertens commented on src/stuf/stuf_zds/templates/stuf_zds/soap/creeerZaak.xml
>                      {% elif initiator.kvk %}
what if there's no `initiator.kvk`, but there is `initiator.vestigingsNummer`?

2022-09-15 15:29 UTC, sergei-maertens approved these changes
I'll rebase this into commits that can be cherry-picked for backport!

2022-09-15 16:17 UTC, merged

2022-09-15 16:28 UTC, sergei-maertens commented
Backported in bfbcbe2b974c31c911b95d1727e620a3bff1f853 and f4d5b8125a02d7ecd86dad8034323dc3b01879e1