[#2197] Token authorisation: core openforms changes
open-formulieren/open-forms pull request #2237
Opened 2022-10-24 12:54 UTC by SilviaAmAm

Part of #2197 

**Changes**
- Add the `pre_requests` registry
- Add a new client which calls the registered pre_requests hooks
- Change the ZGW_CONSUMERS_CLIENT_CLASS setting to point to the new client class

2022-10-24 14:59 UTC, sergei-maertens requested changes

2022-10-24 14:59 UTC, sergei-maertens commented on src/openforms/pre_requests/base.py
> +    def __call__(self, method: str, url: str, **kwargs) -> Any:
I'd make the return type `None` since we don't do anything with it anyway.

2022-10-24 14:59 UTC, sergei-maertens commented on src/openforms/pre_requests/tests/test_clients.py
> +                headers.update({"test": "test"})
A more realistic example would ensure the headers are set:

```suggestion
            def __call__(self, url, method, **kwargs):
                kwargs.setdefault("headers", {})
                kwargs["headers"].update({"test": "test"})
```

2022-10-24 14:59 UTC, sergei-maertens commented on src/openforms/conf/base.py
> +    "openforms.pre_requests",
we don't need to add it to `INSTALLED_APPS` since:

* there are no models
* there is no `AppConfig.ready()` that imports/loads code

2022-10-25 08:45 UTC, sergei-maertens approved these changes
Will you add developer documentation in another PR? :)

2022-10-25 12:10 UTC, SilviaAmAm commented
Yes :)

2022-10-25 12:14 UTC, merged