[Draft] Feature/2314 form designer translations
open-formulieren/open-forms pull request #2353
Opened 2022-11-15 13:07 UTC by stevenbal

Closes #2314

2022-11-28 13:06 UTC, stevenbal commented on src/openforms/js/components/admin/form_design/form-creation-form.js
> +      en: {
Currently the languages and keys are hardcoded, I'm not sure if this is an issue that could be addressed later of or if it needs to be tackled in this PR

2022-11-28 15:43 UTC, stevenbal commented
Some screenshots of the new tabs:

Formdetails:
![Screenshot 2022-11-28 at 16-38-33 formulier wijzigen Open Formulieren](https://user-images.githubusercontent.com/29249171/204319375-e59a5839-54ae-4a56-8955-524e58317474.png)

Formsteps:
![Screenshot 2022-11-28 at 16-38-43 formulier wijzigen Open Formulieren](https://user-images.githubusercontent.com/29249171/204319410-451ed8f9-0c0d-40c6-b942-0050cc9f9857.png)

Confirmation:
![Screenshot 2022-11-28 at 16-42-13 formulier wijzigen Open Formulieren](https://user-images.githubusercontent.com/29249171/204319847-05a95854-1f7e-4616-bdce-a0b4f11dc4ba.png)
![Screenshot 2022-11-28 at 16-42-19 formulier wijzigen Open Formulieren](https://user-images.githubusercontent.com/29249171/204319832-20548393-bd39-4141-a0ac-7e80686933da.png)

Literals:
![Screenshot 2022-11-28 at 16-39-22 formulier wijzigen Open Formulieren](https://user-images.githubusercontent.com/29249171/204319427-41f912cf-2991-4a67-82c9-650d91409265.png)

Tabs should also indicate if there are errors for a specific language
![Screenshot 2022-11-28 at 16-40-28 formulier wijzigen Open Formulieren](https://user-images.githubusercontent.com/29249171/204319440-91fabc03-a81e-4d12-8580-c2b74211295b.png)

2022-11-28 15:49 UTC, stevenbal commented
This PR doesn't implement the formIO component part of https://github.com/open-formulieren/open-forms/issues/2314, because that depends on https://github.com/open-formulieren/open-forms/issues/2315

2022-11-29 14:21 UTC, sergei-maertens requested changes
There are some broad changes/patterns I'd like to see addressed that apply to most of the code:

There is a lot of imperative programming that would really benefit from React's declarative nature. Instead of passing down the props all the way down the tree and then explicitly mapping over languages to build some JSX to then render, I'd rather see some code structure along the lines of:

```jsx
<LanguageTabs>
    <ErrorList />
    <FormRow>...</FormRow>
</LanguageTabs>
```
with the idea that the `LanguageTabs` component repeats its children for every supported language, making the tree structure a lot clearer.

This would also benefit from tracking some values/props in Context rather than having to pass them down via components that don't care about this information, e.g. the `LanguageTabs` component above should then be able to:

```jsx
const {languages, defaultLanguage} = useContext(LanguagesContext);
return languages.map(React.Children.each(children, ...));
```

etc.

I think this effort is too much to address all in this PR and postpone the backend branch further, so maybe it should be addressed in a separate PR so we can go ahead with this first iteration.

2022-11-30 16:28 UTC, sergei-maertens commented
Merging this as is, there's some follow up work to be done which is tracked in #2418

2022-11-30 16:29 UTC, merged