[#2250] fix broken analytics tools
open-formulieren/open-forms pull request #2419
Opened 2022-11-30 15:37 UTC by pi-sigma

- all analytics tools (except Google Analytics) failed to render because the wrong property was tested in the templates
- fixed the templates
- added integration tests for the rendering of analytics snippets

2022-11-30 15:43 UTC, pi-sigma commented
I know it's not best practice to assert string inclusion against a large blob of text (as happens in my tests), but I see no way to zoom in on the scripts with Pyquery, Beautifulsoup or the like to ascertain that a particular snippet is rendered on the page. Should the tests be replaced with functional tests using Selenium, should we leave it as is, or is there some option I've overlooked?

2022-11-30 16:27 UTC, sergei-maertens requested changes

2022-11-30 16:27 UTC, sergei-maertens commented on src/openforms/analytics_tools/templates/analytics_tools/matomo.html
> +{% if analytics_tools_config.enable_matomo_site_analytics %}
```suggestion
{% if analytics_tools_config.is_matomo_enabled %}
```
this pattern repeats - we have an explicit check for:

* tool is configured correctly
* tool is actually turned on

now you're testing only for the latter

2022-11-30 16:27 UTC, sergei-maertens commented on src/openforms/analytics_tools/tests/test_analytics_rendering.py
> +        self.assertIn("googletagmanager", script_text)
to answer your question in the comment - let's give every analytics script an id (e.g. `<script id="analytics-matomo">` and test for that by finding the node with this ID and asserting that it's a script tag. That should be sufficient.

2022-12-01 10:59 UTC, sergei-maertens approved these changes

2022-12-06 09:35 UTC, merged