[Draft] :construction: [#2478] Initial work for FormIO translations refactor
open-formulieren/open-forms pull request #2533
Opened 2023-01-09 13:10 UTC by stevenbal

Fixes #2478

2023-01-26 20:34 UTC, sergei-maertens commented on src/openforms/forms/forms/form_definition.py
> +            "component_translations",
TODO -> this isn't going right now in the admin

2023-01-26 20:35 UTC, sergei-maertens commented on src/openforms/js/components/form/translations.js
> +class TranslationsDataGrid extends Formio.Components.components.datagrid {
TODO: check if we can't enforce this behaviour via options

2023-01-26 20:36 UTC, sergei-maertens commented on src/openforms/js/components/formio_builder/index.js
> +    // FIXME: handle translations?
TODO: should be possible to manage component translations from standalone admin page too

2023-01-26 20:37 UTC, sergei-maertens commented on src/openforms/js/formio_module.js
> +    translationsDataGrid: TranslationsDataGrid,
TODO: check if we can avoid this

2023-01-27 16:38 UTC, sergei-maertens requested changes
Selenium tests are flaky still - old translations may show up

2023-01-27 18:56 UTC, sergei-maertens commented
Ok, all that's left to do is cleaning up the commit history if CI passes

2023-01-27 21:13 UTC, sergei-maertens commented
![image](https://user-images.githubusercontent.com/5518550/215201455-22b69f1a-018a-4634-9fb9-9b1c9b6d51f1.png)

2023-01-30 11:06 UTC, sergei-maertens approved these changes
(just approving to get rid of the 'changes requested' status)

2023-01-30 14:08 UTC, CharString commented on src/openforms/js/components/formio_builder/translation.js
> +  return typeof item.test === 'function';
I wouldn't be surprised if String were function too in javascript xD

2023-01-30 14:20 UTC, CharString commented on src/openforms/js/components/formio_builder/translation.js
> +export const persistComponentTranslations = (container, component) => {
Reading `persistComponentTranslations` elsewhere without context, made me think persistence to the backend. While it's actually moving data from the passed in component to the container... Can't really think of a better name :thinking:

2023-01-30 14:27 UTC, CharString commented on src/openforms/js/components/formio_builder/translation.spec.js
> +    expect(isTranslatableProperty('selectboxes', 'values[420].label')).toBe(true);
Yep. What were they smoking?

2023-01-30 14:28 UTC, CharString commented on src/openforms/scss/components/builder/_builder.scss
> +    min-height: 0;
I don't even want to know...

2023-01-30 14:37 UTC, CharString commented on src/openforms/forms/tests/selenium_tests/test_form_designer.py
> +from openforms.tests.selenium_tests.base import SeleniumTestCase
`base` is a first in the codebase. But "utils" feels off too... Maybe move it to __init__.py. Meh. Base it is...

2023-01-30 14:54 UTC, merged