[#2557] Introduce datetime component
open-formulieren/open-forms pull request #2563
Opened 2023-01-16 12:04 UTC by SilviaAmAm

Fixes #2557 

Front end: https://github.com/open-formulieren/open-forms-sdk/pull/343
Json logic: https://github.com/maykinmedia/json-logic-py/pull/13

2023-01-27 15:19 UTC, CharString requested changes

2023-01-27 15:19 UTC, CharString commented on src/openforms/utils/json_logic/descriptions.py
> +            )
Matching can unpack too:
```suggestion
    match args:
        case [years]:
            return gettext("{years} year(s)").format(**locals())
        case [years, months]:
            return gettext("{years} year(s), {months} month(s)").format(**locals())
        case [years, months, days]:
            return gettext("{years} year(s), {months} month(s), {days} day(s)").format(**locals())
        case [years, months, days, hours]:
            return gettext("{years}y, {months}m, {days}d, {hours}h").format(**locals())
        case [years, months, days, hours, minutes]:
            return gettext(
                "{years}y, {months}m, {days}d, {hours}h, {minutes}min"
            ).format(**locals())
        case [years, months, days, hours, minutes, seconds]:
            return gettext(
                "{years}y, {months}m, {days}d, {hours}h, {minutes}min, {seconds}s"
            ).format(**locals())
        case _:
            raise ValueError("Unexpected amount of arguments. Expected 1-6 got {len(args)}: {args!r}")

```
Should work... 

The error is really needed. If I had to write jsonlogic, I'd want all the help I could get from a compiler.

2023-01-27 15:26 UTC, CharString commented
Should we document the behaviour around daylight savings time changes? I look forward to dismissing DST pain issues with a "won't fix", ask our politicians to stop with this DST nonsense.

2023-01-27 16:00 UTC, SilviaAmAm commented
@CharString which behaviour do you mean? 

Thinking about it, maybe I should have included the timezone in the formatter? :thinking:

2023-01-27 17:52 UTC, CharString commented
> @CharString which behaviour do you mean?

For example adding a delta > 48h to a datetime to a datetime on a Friday before the switch. Not all weekends have 48 hours. Every year there's one with 47 and one with 49.

Or more in our user's terms: 6 weeks is a common delta in Dutch administrative law. Adding a delta of 6*7 days to 17:00 on a day within 6 weeks of a switch will end up on 16:00 or 18:00 on the target day in the timezone that is in effect then.

> Thinking about it, maybe I should have included the timezone in the formatter? thinking

Well... If we format the time in the same timezone as the start datetime... The above will not become apparent. But on the resulting datetime, the timezone has switched. In the local case between CET and CEST.

But... The tests use fixed offset timezones and frozen now()... So CI won't break, so it's not our problem.
Funny, [the guy that caused all this nonsense](https://en.wikipedia.org/wiki/William_Willett) did so because he liked [having some lit time playing golf](uhttps://archive.org/details/seizedaylightcur0000prer)... Golf with Friends anyone? :eyes:

2023-01-27 17:57 UTC, CharString approved these changes

2023-01-27 21:16 UTC, sergei-maertens commented
> > @CharString which behaviour do you mean?
> 
> For example adding a delta > 48h to a datetime to a datetime on a Friday before the switch. Not all weekends have 48 hours. Every year there's one with 47 and one with 49.
> 
> Or more in our user's terms: 6 weeks is a common delta in Dutch administrative law. Adding a delta of 6*7 days to 17:00 on a day within 6 weeks of a switch will end up on 16:00 or 18:00 on the target day in the timezone that is in effect then.
> 
> > Thinking about it, maybe I should have included the timezone in the formatter? thinking
> 
> Well... If we format the time in the same timezone as the start datetime... The above will not become apparent. But on the resulting datetime, the timezone has switched. In the local case between CET and CEST.
> 
> But... The tests use fixed offset timezones and frozen now()... So CI won't break, so it's not our problem. Funny, [the guy that caused all this nonsense](https://en.wikipedia.org/wiki/William_Willett) did so because he liked having some lit time playing golf... Golf with Friends anyone? eyes

Using your days/weeks examples - maybe the result should be rounded to a similar precision? if we're talking days/weeks -> don't bother comparing hours/minutes/seconds, but resolve to the day/date instead.

This depends a lot on internal processes though - is the exact time relevant, or are they only working in times of days? -> let's check with the business before making the code more complicated :)

2023-01-30 16:28 UTC, sergei-maertens commented on src/openforms/forms/api/validators.py
> +            and (operand.operator == "date" or operand.operator == "datetime")
neater would be `operand.operator in ["date", "datetime"]`, but good enough for now

2023-01-30 16:32 UTC, sergei-maertens approved these changes

2023-01-30 17:02 UTC, merged