[Draft] [#2493] Warnings for missing translations in admin
open-formulieren/open-forms pull request #2600
Opened 2023-01-24 09:30 UTC by stevenbal

Fixes #2493

2023-01-31 12:51 UTC, sergei-maertens requested changes

2023-01-31 12:51 UTC, sergei-maertens commented on src/openforms/js/components/admin/form_design/FormStepDefinition.js
> +import React, {useContext} from 'react';
need to clean up some more rebase conflicts

2023-01-31 12:51 UTC, sergei-maertens commented on src/openforms/js/components/admin/form_design/MissingComponentTranslationsWarning.js
> +const LANGUAGES = getSupportedLanguages();
this used to be inside the react component (via jsonScriptToVar) which does DOM operations, and you absolute do not want to do that in React. DOM interaction is comparatively expensive, and having every render to DOM operations removes the advantages from using React.

This is also information that doesn't change once the page is loaded, so evaluating it once at the module level is appropriate.

2023-01-31 12:51 UTC, sergei-maertens commented on src/openforms/js/components/admin/form_design/MissingComponentTranslationsWarning.js
> +      const literals = extractComponentLiterals(component);
refactored using utility from *that other PR*

2023-01-31 12:51 UTC, sergei-maertens commented on src/openforms/js/components/admin/form_design/MissingComponentTranslationsWarning.js
> +    })
PropTypes.object is only good enough when you don't know the shape of the object. Whenever we do (as evidenced here by the prop names that we're reading out in the component), make this explicit.

2023-01-31 12:51 UTC, sergei-maertens commented on src/openforms/js/components/admin/form_design/MissingComponentTranslationsWarning.js
> +  });
Added some more sorting to group/sort by component, then language, then literal. This makes sense as in the UI you open the component, then navigate to a particular language tab and fix all the relevant literals per language.

2023-01-31 12:51 UTC, sergei-maertens commented on src/openforms/forms/admin/form.py
> +        }
I've updated this and seems to work.

2023-01-31 14:35 UTC, sergei-maertens commented
I'm not happy yet with the locations and contents of the warnings (functional aspect), so let's postpone this to 2.2.0 as an improvement. It doesn't prevent us from shipping 2.1.0.

2023-02-06 14:57 UTC, stevenbal commented
I added the top level warning for missing component translations:

![image](https://user-images.githubusercontent.com/29249171/217005226-79602670-2576-45f3-b622-298226ac29a7.png)

I figured it was easier to add an extra warning message than to conditionally add an extra string to the `FormattedMessage` (I'm not sure how that would work)

2023-02-07 12:38 UTC, sergei-maertens requested changes

2023-02-07 12:38 UTC, sergei-maertens commented on src/openforms/js/components/admin/form_design/MissingTranslationsWarning.js
> +  const languages = jsonScriptToVar('languages');
This is not something you should call during component renders because they perform DOM manipulation.

2023-02-07 14:39 UTC, merged