[#2581] Inconsistent dates / datetimes
open-formulieren/open-forms pull request #2614
Opened 2023-01-27 14:45 UTC by SilviaAmAm

Fixes #2581

2023-01-27 16:03 UTC, CharString requested changes
So
```
base_value = cast(
        Optional[Union[datetime, str]],
        glom(data, config["variable"], default=None),
    )
```
should include the `date` type in the Union...

I think instead of this casting, a pattern match is a lot clearer:
```python
base_value = glom(data, config["variable"], default=None)
match base_value:
    case datetime.datetime():
        assert ...
        base_date = timezone.localtime(value=base_value).date()
    case datetime.date():
        base_date = base_value
    case str():
        pass # what happened to this case in the Union?
    case None:
        return None
```

> Never send a human to do a machine's job.
> -- Agent Smith

The only thing worse than an Any type is a wrong guess at a cast.
But maybe this is out of scope for the issue...

2023-01-27 16:55 UTC, CharString approved these changes

2023-01-27 17:08 UTC, CharString commented
@sergei-maertens 
One caveat on second reading:
If `DateConstraintConfiguration` contains information that can help form designers with debugging broken logic. I think we should provide that in the error. But I don't know what helpful information is in scope here.

2023-01-30 15:14 UTC, sergei-maertens commented
> @sergei-maertens One caveat on second reading: If `DateConstraintConfiguration` contains information that can help form designers with debugging broken logic. I think we should provide that in the error. But I don't know what helpful information is in scope here.

Clarified in the office - this is not executed at form-design time, but at submission/form-execution runtime, so there's no validation error stuff relevant. This only concerns sanity checks for input.

2023-01-30 16:11 UTC, sergei-maertens approved these changes

2023-01-30 16:21 UTC, merged