[#2623] Robustness bad variables
open-formulieren/open-forms pull request #2630
Opened 2023-02-01 08:57 UTC by SilviaAmAm

Fixes #2623

2023-02-01 11:06 UTC, CharString requested changes
I think we should assert the logevent if we know we trigger it.

And on a more bird's eye view of the problem we're trying to solve here... Is `valueExpression` even needed? As far as I can see it can be expressed with `map` in the `itemExpression` or since that is missing in our jsonlogic fork: a `reduce` of the `var` with a `merge` on an empty array as the accumulator.

2023-02-01 11:15 UTC, CharString commented
I don't know if this is brand new functionality or if `valueExpression` is in use in the wild.
If new, I'd rather implement a simple `map` and reduce (no pun intended) complexity in this code... Having `map` while strictly not needed, does make expressing cherry picking values off a repeating group *that* much more ergonomic.

And I can see its use in triggers too for step triggers like "Do you have children under the age of 18 in your household." Those would just be a "any" of a "map" of a comparison of birthdates in the repeating group of co-inhabitants. Steps like this exist in tax forms.

2023-02-01 11:18 UTC, SilviaAmAm commented
It is new functionality from the previous PR! https://github.com/open-formulieren/open-forms/pull/2595

I could add the `map` to the JSON logic package and then we could get rid of `valueExpression`!

2023-02-01 11:18 UTC, SilviaAmAm commented on src/openforms/formio/dynamic_config/tests/test_dynamic_options.py
> +        )
I don't think so: atm the log event is triggered if there is no valueExpression and the items are not primitives :thinking:

2023-02-01 11:21 UTC, CharString commented
Great! The most beautiful code, is the  code that doesn't exist... :fire: > :sparkles: in my opinion. :wink:

2023-02-01 14:25 UTC, SilviaAmAm commented
Still needs upgrading json-logic-py: https://github.com/maykinmedia/json-logic-py/pull/15

2023-02-01 14:59 UTC, sergei-maertens requested changes
Had a quick discussion with Chris about this because I was concerned this makes it impossible for us to specify different sources for the values and labels of choices - as we now basically always normalize to a list of strings and every item (string) is used as both value and label.

However, that approach makes it impossible to query other systems based on "system data" (like IDs) and still displaying the human readable label. It should be possible to use a variable with the contents:

```js
[
  {dbId: 1, name: 'Foo'},
  {dbId: 2, name: 'Bar'},
]
```
as the data source for select/checkboxes/radio.

This should ideally result in:

```
<select>
  <option value="1">Foo</option>
  <option value="2">Bar</option>
</select>
```

The same can go for a repeating group with children for example, where you enter the BSN and name as separate fields and use the BSN as value while displaying the name.

Long story short - the map expression should return either a list of strings, which we normalize to a list of two-tuples (value and label are the same then), or a list of two-tuples representing `(value, label)`.

Our gut-feeling is that you can come up with a `map` expression that achieves this, but we'd like to see this confirmed in the implementation and tests.

2023-02-03 15:51 UTC, CharString approved these changes
No real issues. This is fine as is. :+1:

2023-02-06 10:50 UTC, merged