Refactor base StUF utilities/client
open-formulieren/open-forms pull request #2644
Opened 2023-02-02 15:11 UTC by sergei-maertens

Closes #388
Closes #965

* Implemented base client
    * Can be used both as context manager or directly while closing the underlying requests session/resources
    * Abstracts away the details of requests w/r to auth kwargs/mTLS etc.
* Let base client generate common/base context for templates
* Use template inheritance and inclusion for common SOAP/StUF constructs that have nothing to do with the specific domain

2023-02-02 17:29 UTC, sergei-maertens commented on src/openforms/registrations/contrib/stuf_zds/plugin.py
> +        with config.get_client(options) as client:
this should now result in connection pooling :)

2023-02-02 17:31 UTC, sergei-maertens commented on src/stuf/stuf_bg/client.py
> +    sector_namespace = "http://www.egem.nl/StUF/sector/bg/0310"
this is still a bit iffy, will revisit to see if we can make this a bit cleaner

2023-02-02 17:31 UTC, sergei-maertens commented on src/stuf/stuf_bg/client.py
>          logger.debug(
bit funky that this is happening here tbh

2023-02-02 17:35 UTC, sergei-maertens commented on src/stuf/stuf_bg/tests/test_client.py
> +        self.service = StufServiceFactory.create(soap_service__soap_version="1.1")
this one is sketchy - the default is SOAP 1.2, but the stuf BG service always emited `xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"` which is wrong according to the StUF-ZDS template conditional...

However, the assertion below about the content type expects the version to be 1.2. Either the `soapenv` or the content type assertion is wrong?

2023-02-02 17:36 UTC, sergei-maertens commented on src/stuf/stuf_zds/client.py
> +                "gemeentecode": self.options.get("gemeentecode", ""),
there are a lot of tests that don't properly pass in these options :(

I'm also wondering if this should even be part of the base context... The type annotation now at least reports these errors.

2023-02-02 17:37 UTC, sergei-maertens commented on src/stuf/stuf_zds/client.py
> +        _url = self.service.get_endpoint(type=endpoint_type)
bit of duplication and a risk of code going out of sync... this is only used for logging purposes. I'd rather use a requests hook to process/log the response, but that also requires some state :/

2023-02-02 17:38 UTC, sergei-maertens commented on src/stuf/stuf_zds/templates/stuf_zds/soap/creeerZaak.xml
>          xmlns:StUF="http://www.egem.nl/StUF/StUF0301"
namespace mess - StUF-BG defines them on the root element, while StUF-ZDS defines them on the children? Why this inconsistency?

2023-02-02 17:38 UTC, sergei-maertens commented on src/stuf/stuf_zds/templates/stuf_zds/soap/geefZaakDetails_check.xml
> +{% block body %}<ZKN:zakLv01 xmlns:StUF="http://www.egem.nl/StUF/StUF0301" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xmlns:ZKN="http://www.egem
namespace mess - StUF-BG defines them on the root element, while StUF-ZDS defines them on the children? Why this inconsistency?

2023-02-02 17:38 UTC, sergei-maertens commented on src/stuf/stuf_zds/templates/stuf_zds/soap/genereerDocumentIdentificatie.xml
>          xmlns:StUF="http://www.egem.nl/StUF/StUF0301"
namespace mess - StUF-BG defines them on the root element, while StUF-ZDS defines them on the children? Why this inconsistency?

2023-02-02 17:39 UTC, sergei-maertens commented on src/stuf/stuf_zds/templates/stuf_zds/soap/genereerZaakIdentificatie.xml
>          xmlns:StUF="http://www.egem.nl/StUF/StUF0301"
namespace mess - StUF-BG defines them on the root element, while StUF-ZDS defines them on the children? Why this inconsistency?

2023-02-02 17:39 UTC, sergei-maertens commented on src/stuf/stuf_zds/templates/stuf_zds/soap/updateZaak.xml
>          xmlns:ZKN="http://www.egem.nl/StUF/sector/zkn/0310"
namespace mess - StUF-BG defines them on the root element, while StUF-ZDS defines them on the children? Why this inconsistency?

2023-02-02 17:39 UTC, sergei-maertens commented on src/stuf/stuf_zds/templates/stuf_zds/soap/voegZaakdocumentToe.xml
>          xmlns:StUF="http://www.egem.nl/StUF/StUF0301"
namespace mess - StUF-BG defines them on the root element, while StUF-ZDS defines them on the children? Why this inconsistency?

2023-02-02 17:41 UTC, sergei-maertens commented on src/stuf/templates/stuf/includes/security.xml
> +{% if use_wss %}
this was conditional for StUF-ZDS, but always present for StUF-BG (no conditional there). Could break something?

2023-02-02 17:41 UTC, sergei-maertens commented on src/stuf/templates/stuf/soap_envelope.xml
> +{# TODO: use only relevant namespaces #}
See TODO

2023-02-02 17:42 UTC, sergei-maertens commented on src/stuf/templates/stuf/soap_envelope.xml
> +    xmlns:ns="{{ main_namespace }}"
dirty solution -> need to find a nicer way, because the prefixes are actually used in the rest of the template code.

2023-02-02 17:42 UTC, sergei-maertens commented on src/stuf/templatetags/stuf.py
> +def fmt_soap_datetime(d: datetime) -> str:
unused

2023-02-02 17:42 UTC, sergei-maertens commented on src/stuf/templatetags/stuf.py
> +def fmt_soap_time(d: datetime) -> str:
unused

2023-02-02 17:42 UTC, sergei-maertens commented on src/stuf/templatetags/stuf.py
> +TIME_FORMAT = "%H%M%S"
unused

2023-02-02 17:43 UTC, sergei-maertens commented on src/stuf/templatetags/stuf.py
> +DATETIME_FORMAT = "%Y%m%d%H%M%S"
unused

2023-02-02 17:44 UTC, sergei-maertens commented on src/stuf/templatetags/stuf.py
> +        "wss_expires": fmt_soap_date(expires_at),
this just looks plain wrong, why calculate things with second/minute precision to then truncate the time part?

Taken from the StUF-ZDS implementation - the StUF-BG implementation doesn't even format it at all but just dumps the datetime instance into the template context, and in the templates there was no formatting either (just a plain `{{ created }}`)

2023-02-02 17:45 UTC, sergei-maertens commented on src/stuf/templatetags/stuf.py
> +    tijdstip_bericht: datetime | str | None = None,
remove this argument completely - we don't pass it in anywhere and can rely on on-the-fly generation encapsulated inside this tag.

2023-02-03 09:36 UTC, sergei-maertens commented on src/stuf/stuf_bg/tests/test_client.py
> +            SOAP_VERSION_CONTENT_TYPES.get(SOAPVersion.soap11),
geaccepteerd

2023-02-03 09:43 UTC, sergei-maertens commented on src/stuf/stuf_zds/templates/stuf_zds/soap/creeerZaak.xml
>          xmlns:StUF="http://www.egem.nl/StUF/StUF0301"
use them on domain root element

2023-02-03 09:59 UTC, sergei-maertens commented on src/stuf/templatetags/stuf.py
> +        "wss_expires": fmt_soap_date(expires_at),
checked with spec (link via Joeri, https://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0.pdf), they need to be ISO 8601 datetimes

2023-02-03 13:44 UTC, sergei-maertens commented on src/stuf/stuf_bg/client.py
> +    sector_namespace = "http://www.egem.nl/StUF/sector/bg/0310"
Resolved via 0126688d73541bbe5ff157b1114d35cc71426dec

2023-02-03 13:44 UTC, sergei-maertens commented on src/stuf/stuf_zds/templates/stuf_zds/soap/creeerZaak.xml
>          xmlns:StUF="http://www.egem.nl/StUF/StUF0301"
Resolved via 0126688d73541bbe5ff157b1114d35cc71426dec

2023-02-03 13:44 UTC, sergei-maertens commented on src/stuf/stuf_zds/templates/stuf_zds/soap/geefZaakDetails_check.xml
> +{% block body %}<ZKN:zakLv01 xmlns:StUF="http://www.egem.nl/StUF/StUF0301" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xmlns:ZKN="http://www.egem
Resolved via 0126688d73541bbe5ff157b1114d35cc71426dec

2023-02-03 13:44 UTC, sergei-maertens commented on src/stuf/stuf_zds/templates/stuf_zds/soap/genereerDocumentIdentificatie.xml
>          xmlns:StUF="http://www.egem.nl/StUF/StUF0301"
Resolved via 0126688d73541bbe5ff157b1114d35cc71426dec

2023-02-03 13:44 UTC, sergei-maertens commented on src/stuf/stuf_zds/templates/stuf_zds/soap/updateZaak.xml
>          xmlns:ZKN="http://www.egem.nl/StUF/sector/zkn/0310"
Resolved via 0126688d73541bbe5ff157b1114d35cc71426dec

2023-02-03 13:44 UTC, sergei-maertens commented on src/stuf/stuf_zds/templates/stuf_zds/soap/genereerZaakIdentificatie.xml
>          xmlns:StUF="http://www.egem.nl/StUF/StUF0301"
Resolved via 0126688d73541bbe5ff157b1114d35cc71426dec

2023-02-03 13:45 UTC, sergei-maertens commented on src/stuf/stuf_zds/templates/stuf_zds/soap/voegZaakdocumentToe.xml
>          xmlns:StUF="http://www.egem.nl/StUF/StUF0301"
Resolved via 0126688d73541bbe5ff157b1114d35cc71426dec

2023-02-03 13:45 UTC, sergei-maertens commented on src/stuf/templates/stuf/includes/security.xml
> +{% if use_wss %}
Accepted risk

2023-02-03 13:45 UTC, sergei-maertens commented on src/stuf/templates/stuf/soap_envelope.xml
> +{# TODO: use only relevant namespaces #}
Resolved via 0126688d73541bbe5ff157b1114d35cc71426dec

2023-02-03 13:46 UTC, sergei-maertens commented on src/stuf/templates/stuf/soap_envelope.xml
> +    xmlns:ns="{{ main_namespace }}"
Resolved via 0126688d73541bbe5ff157b1114d35cc71426dec

2023-02-03 14:45 UTC, sergei-maertens commented on src/stuf/templatetags/stuf.py
> +        "wss_expires": fmt_soap_date(expires_at),
Fixed via 95f3e1497c39fb59bf4c05dac1d726f8b0cb36d3

2023-02-03 14:47 UTC, sergei-maertens commented on src/stuf/stuf_bg/tests/test_client.py
> +        self.service = StufServiceFactory.create(soap_service__soap_version="1.1")
Using 1.1 is okay, risk accepted. 1.1 is also what's used in practice.

2023-02-04 22:25 UTC, sergei-maertens commented
I want to write some more tests for the `stuf` app and base client by itself - the long term goal is that this can be a standalone package on PyPI if/when other projects need it.

2023-02-06 16:08 UTC, CharString requested changes

2023-02-06 16:08 UTC, CharString commented on src/stuf/tests/test_model.py
> +            service.get_endpoint(str(uuid4()))
Is there a chance of 1 in 2 ** 128 this fails?

Cake if this ever fails in CI!

2023-02-06 16:08 UTC, CharString commented on src/stuf/xml.py
> +"""
It's been years since I last checked defusedxml... Is this the only vector we should worry about?

2023-02-07 15:58 UTC, CharString approved these changes

2023-02-07 15:58 UTC, merged