[Draft] :sparkles: [#2697] Variable injection for service fetch JSON request body
open-formulieren/open-forms pull request #2747
Opened 2023-02-21 16:15 UTC by stevenbal

Based on #2746, that should probably be merged first

Fixes #2697

2023-02-21 16:18 UTC, stevenbal commented on src/openforms/submissions/tests/form_logic/test_binding.py
> +    def test_it_sends_the_body_as_json_with_variables_escape_quotes(self, m):
I'm not sure if there are other examples of values that could potentially break the JSON body

2023-02-21 16:19 UTC, stevenbal commented on src/openforms/submissions/tests/form_logic/test_binding.py
> +        _ = bind(var, {"some_variable": '"bar'})
I'm not sure if there are other examples of values that could potentially break the JSON body

2023-03-22 15:19 UTC, CharString requested changes

2023-03-22 15:19 UTC, CharString commented on src/openforms/submissions/tests/form_logic/test_fetching_form_varaiable_values_from_services.py
> +        self.assertEqual(request.body, b'{"foo": "&quot;bar"}')
```suggestion
        self.assertEqual(request.body, rb'{"foo": "\"bar"}')
```
Maybe check the other values that need to be escaped too:
https://www.json.org/img/string.png

2023-03-22 15:19 UTC, CharString commented on src/openforms/variables/models.py
> +
Does this handle bodies like this?
```
{"naughty_list": ["de broer van Henk de Vries", "{{some_variable}}"]}
```

2023-04-03 15:03 UTC, sergei-maertens requested changes

2023-05-01 09:00 UTC, joeribekker commented
Closed due to refinement.

2023-05-01 09:00 UTC, closed without merging