Feature/3012 multi select items not translating
open-formulieren/open-forms pull request #3072
Opened 2023-05-09 08:20 UTC by bart-maykin

Fixes #3012

2023-05-11 10:48 UTC, CharString requested changes

2023-05-11 11:01 UTC, CharString commented on src/openforms/formio/variables.py
> +    "data",  # type: select
```suggestion
    "data",  # component-type: select
```

`#  type:` is a syntax for type annotations [pep 526](https://peps.python.org/pep-0526/) Can you change the one on "groupLabel" too?

2023-05-26 20:33 UTC, sergei-maertens approved these changes

2023-05-26 20:34 UTC, sergei-maertens commented
Please rebase all Bart's commits into a single one to make it easier to cherry pick this for backporting

2023-05-26 20:34 UTC, sergei-maertens commented on src/openforms/formio/variables.py
> +                        if "label" in item:
there's only partial coverage on these branches, see https://app.codecov.io/gh/open-formulieren/open-forms/pull/3072?src=pr&el=h1

2023-05-30 15:41 UTC, merged