Feature/2606 add support
open-formulieren/open-forms pull request #3125
Opened 2023-05-31 08:28 UTC by bart-maykin

fixes [#2606]

- Added version dropdown in HaalCentraalConfig singleton
- Added version support for v2 api
- Added new atributes for the v2 api
- Made the HaalCentraal plugin work with v1 and v2 of the api

2023-06-09 13:02 UTC, sergei-maertens requested changes
The actual implementation looks okay in terms of functionality, I mostly have a bunch of remarks about the code organization and keeping things small/unit-testable.

2023-06-09 13:02 UTC, sergei-maertens commented on src/openforms/prefill/contrib/haalcentraal/tests/test_plugin.py
> +class HaalCentraalPrefillApiV2Test(TestCase):
See the earlier remark about adding a base class for tests, as it looks like the actual tests are identical.

It's easy to add a regression test for V1 and then forget to add it for V2 or vice versa :thinking:

2023-06-15 09:04 UTC, sergei-maertens requested changes
Please also look at the Codecov annotations for missing test coverage.

Furthermore, the haal centraal plugin `check_config` method also needs updating - it currently doesn't adapt itself to the GET vs. POST of each respective client.

2023-06-19 08:30 UTC, bart-maykin commented on src/openforms/prefill/contrib/haalcentraal/plugin.py
> +            return Attributes.choices
Because the service of haal centraal config is allowed to be empty this will make that get_available_attributes always returns the default value.

2023-06-19 13:44 UTC, sergei-maertens approved these changes

2023-06-19 13:50 UTC, merged