[#2510] Handle no specified url for SoapService
open-formulieren/open-forms pull request #3306
Opened 2023-07-26 12:01 UTC by vaszig

Fixes #2510

2023-07-27 11:49 UTC, sergei-maertens commented on src/openforms/appointments/contrib/jcc/models.py
> +        validators=[validate_service_url_not_empty],
This is deliberate - when configuring StUF-services, you can specify all the necessary endpoints in that model and the SoapService URL is not used anywhere, so it doesn't make sense to configure it. If you make that `blank=False`, people will just enter dummy values and that is then in turn again confusing when debugging the StUF/SOAP calls raising questions like "why is this URL never hit? how can this bullshit URL possibly work?"

So to account for those situations where the URL really is optional, this should remain `blank=True`.

2023-07-31 08:11 UTC, sergei-maertens requested changes

2023-09-11 10:20 UTC, CharString requested changes

2024-01-26 09:45 UTC, sergei-maertens commented
Cleaning up clutter - I don't think this PR is going anywhere and the problem it fixes is not *that* bad, so I'll close this for now.

2024-01-26 09:45 UTC, closed without merging