Confirm ability to use dynamic options in selectboxes
open-formulieren/open-forms pull request #3552
Opened 2023-10-23 16:07 UTC by sergei-maertens

Closes #2629 

Discussed with Joeri - we are not backporting this to older versions.

Added documentation for extending the options of a dropdown/selectboxes/radio field based on particular logic rules. There was a "bug" or oversight in the variables editor that prevents you from setting this up in older versions, but you can use logic rules as a workaround for that to initialize the variable.

* Added stories for some components used in the form designer (this was easier to debug/implement the UX)
* Added documentation with importable example
* The array input widget now has a toggle between list-of-strings nice UI & raw JSON input.
* If the items in the array are anything other than string literals, then the UI is fixed to raw JSON input to avoid data corruption.

2023-10-24 12:51 UTC, CharString requested changes

2023-10-24 12:51 UTC, CharString commented on docs/manual/forms/examples/dynamic_options_3.rst
> +         }
What happens if the submitter repeatedly toggles "Toon optie 3"?

2023-10-24 12:51 UTC, CharString commented on src/openforms/js/components/admin/form_design/variables/VariablesEditor.stories.js
What's the story?
Changing the Prefill-bron or Datatype selections, behaves weird.
If this is supposed to just show the wrapped array thing in a context, I think the story title should reflect that.

2023-10-24 12:51 UTC, CharString commented on src/openforms/js/components/admin/form_design/logic/LiteralValueInput.stories.js
Toggling the "Use raw JSON input" doesn't keep the values I type in. They're tied to the value set in the Contols

2023-10-24 12:58 UTC, sergei-maertens commented on src/openforms/js/components/admin/form_design/logic/LiteralValueInput.js
> +  // structures. In that case, pin the input to use raw JSON.
yep, I missed that. I hope we can migrate the backend JS to TS too in 2024 so that the compiler can at least catch this...

2023-10-24 13:04 UTC, sergei-maertens commented on src/openforms/js/components/admin/form_design/variables/VariablesEditor.stories.js
I tried debugging/developing it through this component which I thought was responsible, while implementing it it turned out that I could isolate `LiteralValueInput` further.

The story is "this component exists and that's about what it looks like" like the majority of the other stories.

> Changing the Prefill-bron or Datatype selections, behaves weird.

It shows the triggered "Actions" in the panel for me, which shows that the `onChange` event handler (prop of the component) was called.

![image](https://github.com/open-formulieren/open-forms/assets/5518550/7066ecc2-589d-4fc5-8002-dd0cd31dcbbd)

I understand that you'd expect the UI to update, but there is no parent state being managed here - the story shows the props and how they get used.

I don't know what a better name is - the storybook convention seems to be to just go with `Default` for a story without interaction tests or special things to just show the component in isolation.

2023-10-24 13:05 UTC, sergei-maertens commented on src/openforms/js/components/admin/form_design/logic/LiteralValueInput.stories.js
intended - the `onChange` handler is called and storybook reflects that:

![image](https://github.com/open-formulieren/open-forms/assets/5518550/c5883ec2-6612-4022-af10-5b9eeb3302a3)

2023-10-26 08:40 UTC, CharString approved these changes

2023-10-26 08:40 UTC, merged