[#4184] Update formstep uuid in logic rules after form copy
open-formulieren/open-forms pull request #4257
Opened 2024-05-02 13:27 UTC by vaszig

Closes #...

**Changes**

- Added a regression test
- Update form copy flow in order to have the correct (new) formstep UUID in the logic rule's actions

**Checklist**

Check off the items that are completed or not relevant.

- Impact on features

  - [ ] Checked copying a form
  - [ ] Checked import/export of a form
  - [ ] Config checks in the configuration overview admin page
  - [ ] Problem detection in the admin email digest is handled

- Release management

  - [ ] I have labelled the PR as "needs-backport" accordingly

- I have updated the translations assets (you do NOT need to provide translations)

  - [ ] Ran `./bin/makemessages.sh`
  - [ ] Ran `./bin/compilemessages_js.sh`

- Commit hygiene

  - [ ] Commit messages refer to the relevant Github issue
  - [ ] Commit messages explain the "why" of change, not the how

2024-05-04 11:29 UTC, sergei-maertens approved these changes

2024-05-04 11:29 UTC, sergei-maertens commented
Does this bug not happen during form import?

2024-05-06 07:36 UTC, sergei-maertens requested changes
I skimmed the import code and I suspect the same problem happens when exporting + importing a form, since a UUID mapping is applied.

2024-05-07 07:17 UTC, vaszig commented
> Does this bug not happen during form import?

I didn't encounter such a problem when I tested a form during import and export but I will try this one more time and have a look at the code.

2024-05-07 08:39 UTC, sergei-maertens approved these changes

2024-05-07 08:39 UTC, merged