Release 3.0.0-alpha.1
open-formulieren/open-forms pull request #4861
Opened 2024-11-26 15:49 UTC by vaszig

Closes #...

**Changes**

**Checklist**

Check off the items that are completed or not relevant.

- Impact on features

  - [ ] Checked copying a form
  - [ ] Checked import/export of a form
  - [ ] Config checks in the configuration overview admin page
  - [ ] Problem detection in the admin email digest is handled

- Release management

  - [ ] I have labelled the PR as "needs-backport" accordingly

- I have updated the translations assets (you do NOT need to provide translations)

  - [ ] Ran `./bin/makemessages_js.sh`
  - [ ] Ran `./bin/compilemessages_js.sh`

- Commit hygiene

  - [ ] Commit messages refer to the relevant Github issue
  - [ ] Commit messages explain the "why" of change, not the how

2024-11-27 15:27 UTC, sergei-maertens requested changes

2024-11-27 15:27 UTC, sergei-maertens commented on CHANGELOG.rst
> +    - Updated cosign configuration docs and manual.
```suggestion
* [:backend:`4320`] Improved the cosign flow and the texts used in cosign flows, while adding more flexibility:

    - You can now use templates specifically for cosigning for the confirmation screen content,
      with the ability to include a 'cosign now' button.
    - You can now use templates specifically for cosigning for the confirmation email subject and content.
    - When links are used in the cosign request email, the cosigner can now directly click through without
      having to enter a code to retrieve the submission.
    - Updated the default templates with better text/instructions.
```

2024-11-27 15:27 UTC, sergei-maertens commented on CHANGELOG.rst
> +  component.
Something more for "project maintenance", no?

2024-11-27 15:27 UTC, sergei-maertens commented on CHANGELOG.rst
> +* Refactored demo plugins configuration to use a modal instead of inline configuration options.
```suggestion
```
not very interesting, and the entry for #4686 can be generalized :)

2024-11-27 15:27 UTC, sergei-maertens commented on CHANGELOG.rst
> +* [:backend:`4707`] Added the option to resize the json widget manually.
```suggestion
* [:backend:`4707`] You can now resize the Json-Logic widgets.
```

2024-11-27 15:27 UTC, sergei-maertens commented on CHANGELOG.rst
> +  react-json-schema-form generated forms.
```suggestion
* [:backend:`4686`} All the registration plugin configuration options are now consistently managed in a 
   modal with better UX.
```

2024-11-27 15:27 UTC, sergei-maertens commented on CHANGELOG.rst
> +* [:backend:`4396`] Added Objects API prefill plugin.
maybe put this closer to the entry for #4693, and put both ticket numbers there?

2024-11-27 15:27 UTC, sergei-maertens commented on CHANGELOG.rst
> +* Fixed tests after removing password component.
```suggestion
```
really belongs together with the change that the password component is removed tbh

2024-11-27 15:27 UTC, sergei-maertens commented on CHANGELOG.rst
> +* [:backend:`4732`] Fixed CSP issues for Expoints/other analytics.
for the issues that were backported (and also added to the master branch changelog), it's best to just copy paste the exact same changelog entries from https://github.com/open-formulieren/open-forms/blob/master/CHANGELOG.rst?plain=1

2024-11-27 15:27 UTC, sergei-maertens commented on CHANGELOG.rst
> +* [:backend:`4810`] Fixed uppercase component variable values turing lowercase. See the
the remark is missing :) though I think it's better to update `src/openforms/upgrades/upgrade_paths.py` and require a minimum version of 2.8.2 before you can upgrade to 3.0, and then we can assume the fix script has been executed.

2024-11-27 15:27 UTC, sergei-maertens commented on CHANGELOG.rst
> +  the backend.
```suggestion
* [:backend:`4772`] Fixed select components with integer values being treated as numbers
  instead of strings.
```

2024-11-27 15:27 UTC, sergei-maertens commented on CHANGELOG.rst
> +* [:backend:`4719`] Improved accessibility in postcode fields.
Bugfix? or new feature? :thinking: "Improved" reads as a new feature, otherwise it should be "Fixed accesibility..."

2024-11-27 15:27 UTC, sergei-maertens commented on CHANGELOG.rst
> +* [:backend:`4802`] Fixed react-select styling issue regarding growing beyond its max inline size.
```suggestion
* [:backend:`4802`] Fixed some dropdowns taking up more horizontal space than intended.
```

2024-11-27 15:27 UTC, sergei-maertens commented on CHANGELOG.rst
> +* Fixed type error in object spread.
```suggestion
* Fixed some pre-configured component configurations not being applied entirely when adding them to the form.
```

2024-11-27 15:27 UTC, sergei-maertens commented on CHANGELOG.rst
> +* [:backend:`4763`] Fixed temporary file uploads that could not be deleted.
```suggestion
* [:backend:`4763`] Fixed temporary file uploads not being delete-able in the admin interface.
```

2024-11-27 15:27 UTC, sergei-maertens commented on CHANGELOG.rst
> +* [:backend:`4546`] Ensured the soft required component integrates well.
```suggestion
* [:backend:`4546`] Fixed the soft-required validation errors being shown in the summary PDF.
```

2024-11-27 15:27 UTC, sergei-maertens commented on CHANGELOG.rst
> +* [:backend:`4849`] Re-recorded VCR cassettes.
```suggestion
```
I know it's a lot of work, but this isn't really useful in the changelog

2024-11-27 15:27 UTC, sergei-maertens commented on CHANGELOG.rst
> +* Updated CHANGELOG with 2.7.10 and 2.8.2 patch releases changes.
```suggestion
```
there's little added value for these kind of items

2024-11-27 15:27 UTC, sergei-maertens commented on CHANGELOG.rst
> +* [:backend:`4431`] Refactored the Objects API v2 handler according to the new mappings implementation.
```suggestion
```
I consider it part of the AddressNL ticket, no need to mention this separately.

2024-11-27 15:27 UTC, sergei-maertens commented on CHANGELOG.rst
> +* Refactor shared utilities to real shared general purpose location.
```suggestion
```
not much value in mentioning this

2024-11-27 15:27 UTC, sergei-maertens commented on CHANGELOG.rst
> +* Bumped lxml html cleaner.
you can summarize this one and the waitress one with a one liner like:

```suggestion
* Upgraded some dependencies to their latest security releases.
```
it's mostly signaling that we're on top of reported security issues in third party dependencies

2024-11-28 07:10 UTC, vaszig commented
Apart from the feedback from your comments, I also moved 4745 from the features to the bugfixes (as it is in the patch releases/master changelog).

2024-11-28 09:27 UTC, sergei-maertens approved these changes

2024-11-28 10:04 UTC, merged