Allow more map interactions and refactor map value datastructures
open-formulieren/open-forms pull request #4953
Opened 2024-12-18 14:45 UTC by robinmolen

Part of #2177
Part of #2178

**Changes**

Changing the datatype of the map component from array to geoJson

**Checklist**

Check off the items that are completed or not relevant.

- Impact on features

  - [x] Checked copying a form
  - [x] Checked import/export of a form
  - [x] Config checks in the configuration overview admin page
  - [x] Problem detection in the admin email digest is handled

- Release management

  - [x] I have labelled the PR as "needs-backport" accordingly

- I have updated the translations assets (you do NOT need to provide translations)

  - [ ] Ran `./bin/makemessages_js.sh`
  - [ ] Ran `./bin/compilemessages_js.sh`

- Dockerfile/scripts

  - [x] Updated the Dockerfile with the necessary scripts from the `./bin` folder

- Commit hygiene

  - [x] Commit messages refer to the relevant Github issue
  - [x] Commit messages explain the "why" of change, not the how

2025-01-08 11:38 UTC, sergei-maertens commented on src/openforms/formio/components/custom.py
> +    )
it's probably a good idea to extract this into a custom field and define it in `openforms.api.fields`:

```py
class GeoJSONCoordinatesField(serializers.ListField):
    child = serializers.FloatField(required=True, allow_null=False),

    def __init__(self, *args, **kwargs):
        kwargs["min_length"] = 2
        kwargs["max_length"] = 2
        super().__init__(*args, **kwargs)
```

which you can then easily (re) use as:

```py
class GeoJSONPointGeometrySerializer(serializers.Serializer):
    coordinates = GeoJSONCoordinatesField()

class GeoJSONLineStringGeometrySerializer(serializers.Serializer):
    coordinates = serializers.ListField(child=GeoJSONCoordinatesField())
```
etc.

I'd even opt to define all of this (including the serializers) in `openforms.api.geojson` rather than `openforms.api.fields` :)

2025-01-08 11:38 UTC, sergei-maertens commented on src/openforms/formio/components/custom.py
> +    }
probably better to define a `models.TextChoices` for the `type` and use an enum-approach rather than regex. This avoids magic strings by centralizing them and makes it clear what we support and what we don't.

Additionaly, `str("Point")` is exactly the same as `"Point"`, so this casting is not needed.

2025-01-08 11:38 UTC, sergei-maertens commented on src/openforms/formio/components/custom.py
> +    geometry = GeoJsonGeometryPolymorphicSerializer()
do we still need the `Feature` container now that circles are dropped? I'd expect that just `GeoJsonGeometryPolymorphicSerializer` is sufficient.

2025-01-08 11:38 UTC, sergei-maertens commented on src/openforms/formio/constants.py
> +    line_string = "LineString", "LineString"
please *always* mark labels as translatable. And I think this also belongs in `openforms.api.geojson` rather than in this file, since nothing about this is formio specific :)

2025-01-08 11:38 UTC, sergei-maertens commented on src/openforms/formio/formatters/custom.py
> +    coordinates: list[float] | list[list[float]] | list[list[list[float]]]
you can create a discriminated union here:

```py
type PointCoordinates = list[float]  # tuple[float, float] would be nicer because that validates the length, list doesn't!

class PointGeometry(TypedDict):
    type: Literal["Point"]
    coordinates: PointCoordinates


class LineGeometry(TypedDict):
    type: Literal["LineString"]
    coordinates: list[PointCoordinates]

...

type GeoJSONGeometry = PointGeometry | LineGeometry | ...
```

2025-01-13 10:57 UTC, robinmolen commented on src/openforms/formio/components/custom.py
> +    )
Ah check, yeah that sounds nice! Yeah a separate `openforms.api.geojson` sounds better than `openforms.api.fields` 👍

2025-01-13 10:58 UTC, robinmolen commented on src/openforms/formio/components/custom.py
> +    }
Check, okay will do

2025-01-13 11:00 UTC, robinmolen commented on src/openforms/formio/components/custom.py
> +    geometry = GeoJsonGeometryPolymorphicSerializer()
Yeah the `type` and `properties` don't add anything right now, so these can be removed. Also the registration backends any need the `geometry`, so we also dont need it for them..

I've already changed this in the sdk (that only the geometry is saved) and will now add it to the backend

2025-01-13 11:02 UTC, robinmolen commented on src/openforms/formio/constants.py
> +    line_string = "LineString", "LineString"
Ah okay, i thought translatable didn't add anything here, seeing these are constants in the code.. But yeah, i'll add it (and take a look around to see where this is used/shown)

Yeah i'll move it to `openforms.api.geojson` 👍

2025-01-13 11:05 UTC, robinmolen commented on src/openforms/formio/formatters/custom.py
> +    coordinates: list[float] | list[list[float]] | list[list[list[float]]]
Ah okay, yeah thats a lot better.. I was struggling with this.

Also a lot nicer that `Literal` is an option here.. I didn't know that this was possible 👌

2025-01-13 13:36 UTC, sergei-maertens commented on src/openforms/formio/constants.py
> +    line_string = "LineString", "LineString"
API documentation would pick up on these, for instance. But even if they're not shown anywhere right now, they may be in the future and then it's best if the translations are already there.

2025-01-15 14:26 UTC, sergei-maertens requested changes
Might be a good idea to disable prettier on JSON files, I had to do the same for markdown and HTML too :wink:

2025-01-15 14:26 UTC, sergei-maertens commented on src/openforms/formio/tests/validation/test_map.py
> +                self.assertEqual(error_codes, error_code)
I don't understand this `_recursive_get_error_code` and that's not good when I'm trying to read/debug a test.

what I expect to see here in the assertions is this:

```py
error = extract_error(errors["foo"], "coordinates")
self.assertEqual(error.code, error_code)
```

2025-01-15 14:26 UTC, sergei-maertens commented on src/openforms/formio/tests/validation/test_map.py
>                  self.assertIn(component["key"], errors)
```suggestion
                self.assertIn("foo", errors)
```
I don't like this indirection in tests :) there's only a single component used in all the cases - it'd be a different story if you're looping over components with different keys.

2025-01-15 14:26 UTC, sergei-maertens commented on src/openforms/formio/tests/validation/test_map.py
> +            ),
I'd break these out into separate, explicit `subTest` cases that are not done in the forloop, so you can avoid having to recurse to get error codes. The problem with recursion is that you have no control about the depth here, and we are very specifically looking at a particular depth/location of the error

So the first case would become something like:

```py
coordinate_errors = extract_error(errors["foo"], "coordinates")
self.assertIsInstance(coordinate_errors, list)
self.assertEqual(len(coordinate_errors), 1)
self.assertEqual(coordinate_errors[0].code, "not_a_list")
```
and this yields a much more simple (and thus easier to debug/maintain) test

2025-01-15 14:26 UTC, sergei-maertens commented on src/openforms/formio/tests/validation/test_map.py
> +def _recursive_get_error_code(error):
it should be possible to rewrite everything to be more explicit which makes this helper obsolete - see further remarks.

Test code should ideally be readable by absolute beginner developers that barely know to write an if/else statement and give them the feeling they understand what's going on. So, dead-simple!

2025-01-15 14:26 UTC, sergei-maertens commented on src/openforms/formio/tests/validation/test_map.py
> +            ),
same as earlier :)

2025-01-15 14:26 UTC, sergei-maertens commented on src/openforms/formio/tests/validation/test_map.py
> +                self.assertIn(component["key"], errors)
```suggestion
                self.assertIn("foo", errors)
```

2025-01-15 14:26 UTC, sergei-maertens commented on src/openforms/formio/tests/validation/test_map.py
> +                self.assertEqual(error.code, error_code)
```suggestion
                self.assertFalse(is_valid)
                error = extract_error(errors["foo"]["coordinates"][0], 0)
                self.assertEqual(error.code, error_code)
```

2025-01-15 14:26 UTC, sergei-maertens commented on src/openforms/formio/tests/validation/test_map.py
I probably missed some spots, but the pattern of remarks is to be applied to all the tests of course.

2025-01-15 14:26 UTC, sergei-maertens commented on src/openforms/formio/formatters/custom.py
> +class PointGeometry(TypedDict):
wouldn't it make more sense to define these types in `src/openforms/api/geojson.py` too? Ultimately these are the types that match the serializers.

Otherwise I'd say to put them in `openforms.typing`.

2025-01-15 14:26 UTC, sergei-maertens commented on src/openforms/registrations/contrib/objects_api/submission_registration.py
> +    return value
that name does not match what the value has - since the value is now any geojson geometry. It's also not doing anything, so isn't it better to just remove it entirely and use the value directly?

2025-01-15 14:26 UTC, sergei-maertens commented on src/openforms/registrations/contrib/zgw_apis/plugin.py
> +    return value
obsolete

2025-01-16 15:55 UTC, robinmolen commented
> Might be a good idea to disable prettier on JSON files, I had to do the same for markdown and HTML too 😉

Ah yeah, probably best to add those to the .prettierignore 🙂 (just to solve it project wide)
I'll make a PR for it

2025-01-16 15:57 UTC, robinmolen commented on src/openforms/formio/components/custom.py
> +from ...api.geojson import GeoJsonGeometryPolymorphicSerializer
Check, i'll change it. Just wondering, why not just use absolute imports for everything?

2025-01-16 22:07 UTC, sergei-maertens commented on src/openforms/formio/components/custom.py
> +from ...api.geojson import GeoJsonGeometryPolymorphicSerializer
Django apps are supposed to be self-contained and it does happen that we lift out code into a separate library. The imports then usually keep working because you take an entire directory and move it somewhere else. If you use (project-specific) absolute imports, then you have a lot of find-and-replace to do.

That's the official reasons - the unofficial one is that absolute imports and relative imports are different blocks with isort and they make it clear when you're importing stuff from another app vs. importing from the same app, and that makes it easier to check if people respect the convention to not import private API from other apps (those imports should go through `service.py` ideally).

2025-01-17 11:07 UTC, sergei-maertens commented
> > Might be a good idea to disable prettier on JSON files, I had to do the same for markdown and HTML too 😉
> 
> Ah yeah, probably best to add those to the .prettierignore 🙂 (just to solve it project wide) I'll make a PR for it

Let's enable prettier on json files inside `src/openforms/js` and disable in other locations.

2025-01-20 10:51 UTC, robinmolen commented on src/openforms/formio/formatters/custom.py
> +class PointGeometry(TypedDict):
I thought that these should remain near the `MapFormatter`, seeing how these types are only used for this class.
And also to keep the code uniform to the `AddressNLFormatter` / `AddressValue` implementation.

But sure, i can move them

2025-01-20 10:52 UTC, robinmolen commented on src/openforms/registrations/contrib/objects_api/submission_registration.py
> +    return value
Yeah these are now obsolete.. Will remove

2025-01-20 14:27 UTC, robinmolen commented on src/openforms/formio/components/custom.py
> +from ...api.geojson import GeoJsonGeometryPolymorphicSerializer
Okay, check check. I'll keep it in mind

2025-01-20 14:32 UTC, robinmolen commented on src/openforms/formio/tests/validation/test_map.py
> +                self.assertEqual(error_codes, error_code)
Yeah i thought that this would simplify things for the multi-dimensional errors, but i totally get your point..

I've removed this function and cleaned the tests up

2025-01-20 14:35 UTC, robinmolen commented on src/openforms/formio/tests/validation/test_map.py
> +            ),
Yeah, this creates a level of obscurity...

I've removed that recursion function and separated the tests a bit. I think/hope this solves/removes the obscurity problems..

2025-01-20 14:41 UTC, robinmolen commented on src/openforms/registrations/contrib/objects_api/submission_registration.py
> +from openforms.formio.formatters.custom import GeoJsonGeometry
With the removal of the `_point_coordinate` function, this import was no-longer needed. So this has been removed as well.

2025-01-21 14:39 UTC, sergei-maertens commented on src/openforms/formio/formatters/custom.py
> +type MapValue = PointGeometry | LineStringGeometry | PolygonGeometry
this is the ideal compromise - it keeps the stuff that's not specific to map components in a generic place while still refining it sufficiently within the map component context

2025-01-21 14:41 UTC, sergei-maertens approved these changes

2025-01-22 11:24 UTC, merged