Feature/4908 json registration backend
open-formulieren/open-forms pull request #4956
Opened 2024-12-19 10:17 UTC by viktorvanwijk

Closes #4908

**Changes**

Add registration backend plugin that converts submitted form data to JSON and sends it to a specified API endpoint

**Checklist**

Check off the items that are completed or not relevant.

- Impact on features

  - [x] Checked copying a form
  - [x] Checked import/export of a form
  - [x] Config checks in the configuration overview admin page
  - [x] Problem detection in the admin email digest is handled

- Release management

  - [x] I have labelled the PR as "needs-backport" accordingly

- I have updated the translations assets (you do NOT need to provide translations)

  - [x] Ran `./bin/makemessages_js.sh`
  - [x] Ran `./bin/compilemessages_js.sh`

- Dockerfile/scripts

  - [x] Updated the Dockerfile with the necessary scripts from the `./bin` folder

- Commit hygiene

  - [x] Commit messages refer to the relevant Github issue
  - [x] Commit messages explain the "why" of change, not the how

2025-01-02 11:44 UTC, sergei-maertens requested changes

2025-01-02 11:44 UTC, sergei-maertens commented on src/openforms/js/components/admin/form_design/registrations/json/fields/FormVariablesSelect.js
This entire file is likely obsoleted by the existing `VariableSelection` component. If I'm wrong, I'll be happy to hear why! :smile:

2025-01-02 11:44 UTC, sergei-maertens commented on src/openforms/js/components/admin/form_design/registrations/json/fields/RelativeAPIEndpoint.js
> +        <TextInput id="id_relativeApiEndpoint" {...fieldProps} />
```suggestion
        <TextInput {...fieldProps} />
```
I *think* it's automatically managed by the `Field` and `TextInput` components.

2025-01-02 11:44 UTC, sergei-maertens commented on src/openforms/js/components/admin/form_design/registrations/json/fields/ServiceSelect.js
> +      >
```suggestion
      <Field
        name="service"
        label={
          <FormattedMessage
            description="JSON registration options 'serviceSelect' label"
            defaultMessage="Service"
          />
        }
        helpText={
          <FormattedMessage
            description="JSON registration options 'serviceSelect' helpText"
            defaultMessage="Which service to send the data to"
          />
        }
        required
        noManageChildProps
      >
```
* label should be bold to indicate it's a required field
* `noManageChildProps` should be the default but we can't do that yet because of all the existing code :grimacing: it avoids some of the `Field` props being manipulated and passed down to the child element (`ReactSelect` in this case)

2025-01-02 11:44 UTC, sergei-maertens commented on src/openforms/registrations/contrib/json/apps.py
> +# TODO-4908: maybe rename to FVaJ (Form Variables as JSON) or similar?
I quite like `JSONDumpAppConfig`

2025-01-02 11:44 UTC, sergei-maertens commented on src/openforms/registrations/contrib/json/config.py
> +    )
I'd name this `path` similar to the `ServiceFetchConfiguration.path` field.

Additionally, we need some input validation here (or at the minimum when making the request), see for example `openforms.variables.validators.validate_path_context_values`. Essentially, if an admin configures an API root of `/foo/bar`, some configuring a form should not be able to perform path traversal to make a call to `/baz` for example.

2025-01-02 11:44 UTC, sergei-maertens commented on src/openforms/registrations/contrib/json/config.py
> +        child=FormioVariableKeyField(max_length=50),
```suggestion
        child=FormioVariableKeyField(),
```
`key` on `FormVariable` has no length limits (it's `models.TextField`), so we can't add such constraints as it would exclude certain variables from being sent.

2025-01-02 11:44 UTC, sergei-maertens commented on src/openforms/registrations/contrib/json/config.py
> +    form_variables: Required[list[str]]
```suggestion
    service: Service
    relative_api_endpoint: str
    form_variables: list[str]
```
`Required` is the default, unless you specify `total=False` on the `TypedDict`.

If you specify `default=""` on the relative API endpoint field, then you also have the guarantee that the key will always be present, and that gives the most ergonomic type definition (nice and strict).

2025-01-02 11:44 UTC, sergei-maertens commented on src/openforms/registrations/contrib/json/models.py
I don't think we need a global configuration at all tbh!

2025-01-02 11:44 UTC, sergei-maertens commented on src/openforms/registrations/contrib/json/plugin.py
> +        }
You can grab the static variables from the submission variables state too, and build up what needs to be processed before doing the processing.

```py
state = submission.load_submission_value_variables_state()

all_values: JSONObject = {
    **variables_state.get_static_data(),
    **state.get_data(),  # dynamic values from user input
}
values_to_register = {
    key: value 
    for key, value in all_values.items()
    if key in options["form_variables"]
}
```

For the attachment processing, there's a bug if you have multiple file uploads - now the previous uploads get overwritten. So, depending on if the component is `multiple` True/False, you need to handle an array of uploads or just a single upload. I'd recommend setting up component-specific processing like in the Objects API: https://github.com/open-formulieren/open-forms/blob/a9506354c37e8c04a32104a740f61512fcaa5aa1/src/openforms/registrations/contrib/objects_api/submission_registration.py#L574

2025-01-02 11:44 UTC, sergei-maertens commented on src/openforms/registrations/contrib/json/plugin.py
> +                options.get("relative_api_endpoint", ""),
this requires some run-time validation just to be sure :)

2025-01-02 11:44 UTC, sergei-maertens commented on src/openforms/registrations/contrib/json/plugin.py
> +                headers={"Content-Type": "application/json"},
I believe this is done automatically by requests if you specify the `json` kwarg.

2025-01-02 11:44 UTC, sergei-maertens commented on src/openforms/registrations/contrib/json/plugin.py
> +        ]
I can't think of anything meaningful to config check, so it's not relevant for this plugin, I think.

2025-01-02 15:49 UTC, viktorvanwijk commented on src/openforms/js/components/admin/form_design/RegistrationFields.stories.js
> +    ],
Looking at the model  `FormVariable` and serializer `FormVariableSerializer`, it seems like I could actually leave out 'formDefinition' and 'dataFormat' as well, but I will add everything for clarity

2025-01-03 09:00 UTC, viktorvanwijk commented on src/openforms/js/components/admin/form_design/registrations/json/JSONSummaryHandler.js
> +  }
Storybook complains about STATIC_URL being not defined in `BooleanIcon`. Where should I add this?

2025-01-03 09:41 UTC, viktorvanwijk commented on src/openforms/js/components/admin/form_design/registrations/json/fields/ServiceSelect.js
> +      >
Also add both to `FormVariableSelect` then?

2025-01-06 13:44 UTC, sergei-maertens commented on src/openforms/js/components/admin/form_design/registrations/json/JSONOptionsForm.js
> +    formVariables: PropTypes.arrayOf(PropTypes.string),
yes! the names in the serializer and data you send in the options have to match :)

2025-01-16 09:43 UTC, viktorvanwijk commented on src/openforms/registrations/contrib/json/config.py
> +    )
`validate_path_context_values` only checks if the path equals `'..'`. Wouldn't it be better to do a `startswith('..')`, or isn't that necessary?

2025-01-16 09:56 UTC, viktorvanwijk commented on src/openforms/registrations/contrib/json/plugin.py
> +        }
In the current implementation, the attachments are added to a dictionary `{'<original_file_name>': '<base64_content>'}`. I liked the consistency better than in the case of switching between a string and list of strings. I wasn't completely sure about the original file name, though. As far as I understand, they are not unique in the database, but they are unique for a particular file-upload component as you can't upload files with the same name. Any thoughts on this?

2025-01-16 10:42 UTC, sergei-maertens commented on src/openforms/registrations/contrib/json/plugin.py
> +        }
> but they are unique for a particular file-upload component, as you can't upload files with the same name

I didn't know that is the current behaviour! So it's definitely not a deliberate thing.

2025-01-16 11:10 UTC, viktorvanwijk commented on src/openforms/registrations/contrib/json/plugin.py
> +        }
After discussion: file data will be sent as an object with `{"file_name": <file_name>, "content": <base64_content>}`. In case of multiple files, the data is a list containing this object for each submitted file.

2025-01-21 10:05 UTC, sergei-maertens commented on src/openforms/js/components/admin/form_design/registrations/json_dump/fields/Variables.js
> +          includeStaticVariables={true}
```suggestion
          includeStaticVariables
```
this is equivalent in JSX - no need to change this now, but for future code this is the idiomatic way to specify true boolean prop values

2025-01-21 10:52 UTC, sergei-maertens requested changes

2025-01-21 10:52 UTC, sergei-maertens commented on src/openforms/registrations/contrib/json_dump/config.py
> +    )
If I enter a path `../bar` when the service has an api root `example.com/foo`, then there is indeed no path traversal happening which is good, however, when I add a safe path, it's not making the correct API call:

```py
>>> from openforms.registrations.contrib.json_dump.plugin import *
>>> service = Service.objects.get(pk=17)
>>> service.api_root
'https://example.com/api/v2/'
>>> data = {"service": service.pk, "path": "nested/404", "variables": ["today"]}
>>> serializer = JSONDumpOptionsSerializer(data=data)
>>> serializer.is_valid()
True
>>> options = serializer.validated_data
>>> options
{'service': <Service: [ORC (Overige)] Objecten Maykin test>, 'path': 'nested/404', 'variables': ['today']}
>>> plugin.register_submission(submission, options)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    plugin.register_submission(submission, options)
  File "/home/bbt/code/open-forms/src/openforms/registrations/contrib/json_dump/plugin.py", line 69, in register_submission
    res.raise_for_status()
  File "/home/bbt/.virtualenvs/open-forms/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://example.com/api/v2/nested%2F404
```

this is slightly different than service fetch - there we support template expressions for the path, here we don't do that. with service fetch, `{{ some_variable }}` is problematic because it can contain slashes (or literally be `..`) and then they need to be URL quoted, but since we only accept literal values, we shouldn't do URL quoting, and that makes it that any `..` in the `path` should probably be blocked (so the validator can just check for `if ".." in value`).

2025-01-21 10:52 UTC, sergei-maertens commented on src/openforms/registrations/contrib/json_dump/plugin.py
> +    ) -> dict:
bare dicts are not very useful because you have no idea about the key type or the value type, so at the minimum I would declare this as `dict[str, Any]`. However, we know that the return value must be JSON serializable because it gets stored in a `JSONField`, so you can use `openforms.typing.JSONObject` as type hint which limits the keys to `str` type and the values to primitives & json objects/arrays.

```suggestion
) -> JSONObject:
```

2025-01-21 10:52 UTC, sergei-maertens commented on src/openforms/registrations/contrib/json_dump/plugin.py
> +from openforms.forms.utils import to_json
this is a private utility because it's not exported by `openforms.forms.service`.

2025-01-21 10:52 UTC, sergei-maertens commented on src/openforms/registrations/contrib/json_dump/plugin.py
> +        json = to_json({"values": values, "schema": schema})
you can just go for `json.dumps(..., cls=DjangoJSONEncoder)`, DRY is not a problem here

2025-01-21 10:52 UTC, sergei-maertens commented on src/openforms/registrations/contrib/json_dump/plugin.py
> +        submission.registration_result = result = {}
`submission.registration_result` automatically gets written with the return value of `register_submission`, see https://github.com/open-formulieren/open-forms/blob/794bbdae3c62eb4e4ce429661b402b57f24f4605/src/openforms/registrations/tasks.py#L338

```suggestion
```

2025-01-21 10:52 UTC, sergei-maertens commented on src/openforms/registrations/contrib/json_dump/plugin.py
> +            path = validate_path_context_values(options.get("path", ""))
so this will need a different sanity check - I don't think the existing validator is really re-usable so fine to just do:

```suggestion
            if ".." in (path := options["path"]):
                raise SuspiciousOperation("Possible path traversal detected")
```

Additionally, the `default = ""` on the `path` serializer field matches the `Options` typedict which guarantees that the `path` key exists in the options, so you don't need to `options.get(...)`, you can access it directly: `options[...]` which simplifies the code a bit and removes some edge cases to handle.

2025-01-21 10:52 UTC, sergei-maertens commented on src/openforms/registrations/contrib/json_dump/plugin.py
> +            result["api_response"] = res.json()
```suggestion
            return {"api_response": res.json()}
```

2025-01-21 10:52 UTC, sergei-maertens commented on src/openforms/registrations/contrib/json_dump/plugin.py
> +                    values[key] = encoded_attachments
I think this is wrong and the decision needs to be made purely based on `multiple`. Example cases for a key `file` / `files`:

* multiple uploads, none provided: `{"files": []}`
* multiple uploads, one provided: `{"files": [{...}]}`
* multiple uploads, multiple provided: `{"files": {...}, {...}]}`
* single upload, none provided: `{"file": null}`
* single upload, file provided: `{"file": {...}}`

This keeps the data type consistent and you can give guarantees that an object will always have the `file_name` and `content` keys.

2025-01-21 10:52 UTC, sergei-maertens commented on src/openforms/registrations/contrib/json_dump/tests/test_backend.py
> +        set_submission_reference(submission)
it's better DX to pass the `with_public_registration_reference=True` trait to the `SubmissionFactory` :)

2025-01-21 10:52 UTC, sergei-maertens commented on src/openforms/registrations/contrib/json_dump/tests/test_backend.py
> +            service=(ServiceFactory(api_root="http://localhost:80/")),
```suggestion
            service=(ServiceFactory.create(api_root="http://localhost:80/")),
```
please always make the `.create` / `.build` explicit so we see if we hit the DB or not. Also, you can create this service in the `setUpTestData` classmethod so it only runs once for the entire test case - the exact service does not influence the behaviour of the test so it's okay to move it in the setup method(s).

2025-01-21 10:52 UTC, sergei-maertens commented on src/openforms/registrations/contrib/json_dump/tests/test_backend.py
> +                "lastName": "Checking",
Plan F?

2025-01-21 10:52 UTC, sergei-maertens commented on src/openforms/registrations/contrib/json_dump/tests/test_backend.py
> +from openforms.submissions.public_references import set_submission_reference
this is not public API and should not be imported outside the submission app :-)

2025-01-21 10:52 UTC, sergei-maertens commented on src/openforms/registrations/contrib/json_dump/tests/test_backend.py
> +class JSONDumpBackendTests(OFVCRMixin, TestCase):
Can you add a test for a `nested/path` endpoint? You'll have to update the Flask app for that too of course.

2025-01-21 10:52 UTC, sergei-maertens commented on src/openforms/registrations/contrib/json_dump/tests/test_backend.py
> +        json_form_options = dict(
please don't use the `dict(...)` constructor - instead use literal dicts and add the type annotation for how the option should look like so we type-check them properly.

I'd also like to see the whole `json_dump` app added to the `pyright.pyproject.toml` config file so we type check this code in CI too.

2025-01-21 10:52 UTC, sergei-maertens commented on src/openforms/registrations/contrib/json_dump/tests/test_backend.py
> +        res = json_plugin.register_submission(submission, json_form_options)
```suggestion
        result = json_plugin.register_submission(submission, json_form_options)
```
let's use proper variable names

2025-01-21 10:52 UTC, sergei-maertens commented on src/openforms/registrations/contrib/json_dump/tests/test_backend.py
> +                glom(res, "api_response.data.values.file.content")
please don't use glom if you can get by with simple access - `result["api_response"]["data"]["values"]["file"]["content"]` is much easier to understand the actual data structure.

Glom is great for dynamic/unknown stuff and transforming data structures outside of our control into something workable, but avoid it otherwise and go for predictable and obvious code, especially in tests.

2025-01-21 10:52 UTC, sergei-maertens commented on src/openforms/registrations/contrib/json_dump/tests/test_backend.py
> +    def test_path_traversal_attack(self):
you can create some variants here and loop over them, using `self.subTest(...)` E.g. an example with `foo/../bar` or `foo..` should be blocked.

2025-01-21 10:52 UTC, sergei-maertens commented on src/openforms/registrations/contrib/json_dump/tests/test_config.py
> +            validate_path("..")
IMO this is too much implementation detail testing - instead test that the serializer blocks suspicious paths as that is our interface with/to the frontend/UI and even the registration tasks use the configuration serializers to create the options dict.

2025-01-21 15:29 UTC, sergei-maertens commented on src/openforms/registrations/contrib/json_dump/plugin.py
> +    ) -> dict:
for future checking: type checker didn't agree :)

2025-01-21 15:35 UTC, viktorvanwijk commented on src/openforms/js/components/admin/form_design/registrations/json_dump/fields/Variables.js
> +          closeMenuOnSelect
Yeah you're right, removed one too many :grimacing:

2025-01-21 16:02 UTC, sergei-maertens approved these changes

2025-01-21 16:14 UTC, merged