Prepare release 3.0.0
open-formulieren/open-forms pull request #4963
Opened 2024-12-20 15:22 UTC by vaszig

Closes #4920 partly
Requires open-formulieren/open-forms-sdk#759

**Changes**

**Checklist**

Check off the items that are completed or not relevant.

- Impact on features

  - [ ] Checked copying a form
  - [ ] Checked import/export of a form
  - [ ] Config checks in the configuration overview admin page
  - [ ] Problem detection in the admin email digest is handled

- Release management

  - [ ] I have labelled the PR as "needs-backport" accordingly

- I have updated the translations assets (you do NOT need to provide translations)

  - [ ] Ran `./bin/makemessages_js.sh`
  - [ ] Ran `./bin/compilemessages_js.sh`

- Dockerfile/scripts

  - [ ] Updated the Dockerfile with the necessary scripts from the `./bin` folder

- Commit hygiene

  - [ ] Commit messages refer to the relevant Github issue
  - [ ] Commit messages explain the "why" of change, not the how

2025-01-07 13:41 UTC, sergei-maertens commented on CHANGELOG.rst
> +  backends.
```suggestion
* [:backend:`4853`, :backend:`4899`] Fixed empty optional configuration fields not 
   passing validation in multiple registration backends.
```

2025-01-07 13:43 UTC, sergei-maertens commented on CHANGELOG.rst
> +* Fixed stories concerning bootstrap.
```suggestion
* Improved the Storybook setup to be closer to the actual Django admin usage.
```

2025-01-07 13:43 UTC, sergei-maertens commented on CHANGELOG.rst
> +* Removed automatic patching for `cosign_information` template tag.
I think this can go to the breaking changes section.

2025-01-07 13:43 UTC, sergei-maertens commented on CHANGELOG.rst
> +* Updated browserslist package.
Leave this one out, it just affects which CSS prefixed and modern-to-old-JS conversions are required.

2025-01-07 13:44 UTC, sergei-maertens commented on CHANGELOG.rst
> +* Removed legacy component translations serializer fields.
This one is part of #3283, so can be left out.

2025-01-07 13:45 UTC, sergei-maertens commented on CHANGELOG.rst
> +* [:backend:`4785`] Upgraded django-digid-eherkenning to 0.18.0 and updated documentation.
You can move this to features and rephrase it as:

```suggestion
* [:backend:`4785`] Updated the eHerkenning metadata generation to match the latest standard version(s).
```

2025-01-07 13:45 UTC, sergei-maertens commented on CHANGELOG.rst
> +    - Made form definition name read only.
Belongs in "breaking changes"

2025-01-07 13:45 UTC, sergei-maertens commented on CHANGELOG.rst
> +* [:backend:`4920`] Updated backend and frontend translations.
can be left out

2025-01-07 13:46 UTC, sergei-maertens commented on CHANGELOG.rst
> +* Improved test flakiness.
```suggestion
* Reduced flakiness in test suite.
```

2025-01-07 13:46 UTC, sergei-maertens commented on CHANGELOG.rst
> +* Removed unused uiSchema property from registration fields.
```suggestion
* Removed unused ``uiSchema`` property from registration fields.
```

2025-01-07 13:47 UTC, sergei-maertens commented on CHANGELOG.rst
> +* Bumped Django to 4.2.17 patch release.
Might be good to do list item "* Updated backend dependencies" and then list the individual entries within that item, and do a similar thing for the frontend dependencies (if relevant)

2025-01-07 13:47 UTC, sergei-maertens commented on CHANGELOG.rst
> +* [:backend:`4771`] Deprecated price logic rules (see breaking changes section for further instructions).
```suggestion
* [:backend:`4771`] Removed price logic rules (see breaking changes section for further instructions).
```
and can go in the breaking changes section too

2025-01-08 10:33 UTC, sergei-maertens requested changes

2025-01-08 10:33 UTC, sergei-maertens commented on CHANGELOG.rst
> +* [:backend:`4771`] Deprecated price logic rules.
```suggestion
* [:backend:`4771`] Removed price logic rules in favour of normal logic rules.
```

2025-01-08 10:33 UTC, sergei-maertens commented on CHANGELOG.rst
> +* [#4969] Improved the UX of the form designer:
```suggestion
* [:backend:`4969`] Improved the UX of the form designer:
```

2025-01-08 10:33 UTC, sergei-maertens commented on CHANGELOG.rst
> +        * [:backend:`4978`] Made v2 config the default one.
```suggestion
        * [:backend:`4978`] The "variables mapping" configuration is now the default - this does not affect existing forms.
```

2025-01-08 10:33 UTC, sergei-maertens commented on CHANGELOG.rst
> +          and pre-registration.
```suggestion
        * [:backend:`4398`] You can now update a referenced existing object rather than create a new record.
          When the object is being updated, the BSN of the authenticated user is verified against the existing
          object data.
```

2025-01-08 10:33 UTC, sergei-maertens commented on CHANGELOG.rst
> +          - Refactored ObjectTypeVersionSelect.
Belongs in the prefill group, not registration :)

```suggestion
        * [:backend:`4396`, :backend:`4693`, :backend:`4608`, :backend:`4859`] You can now configure a variable
          to be prefilled from the Objects API (a.k.a. "product prefill"):

          - It's possible to assign individual properties from the object type to particular form variables.
          - To avoid duplicating configuration, you can copy the configuration from a configured registration
            backend.
```

2025-01-08 10:33 UTC, sergei-maertens commented on CHANGELOG.rst
> +          configuration.
```suggestion
        * [:backend:`4319`] You can now provide a custom document title for StUF-ZDS via the component
          configuration.
```

2025-01-08 10:33 UTC, sergei-maertens commented on CHANGELOG.rst
> +    * Added documentation for product prefill in user manual (examples are also provided).
```suggestion
    * Added documentation for product prefill in user manual.
```

2025-01-08 10:33 UTC, sergei-maertens commented on CHANGELOG.rst
> +        *
Move the entries that are now in registration plugins here :)

2025-01-08 10:33 UTC, sergei-maertens commented on CHANGELOG.rst
> +        * [:backend:`3457`] Custom `title` and `com` parameters can now be defined in Ogone payment plugin.
```suggestion
        * [:backend:`3457`] Custom ``title`` and ``com`` parameters can now be defined in Ogone payment plugin.
```

2025-01-08 10:33 UTC, sergei-maertens commented on CHANGELOG.rst
> +* [:backend:`2173`] The map component now supports using a different background/tile layer
```suggestion
* [:backend:`2173`] The map component now supports using a different background/tile layer.
```

2025-01-08 10:33 UTC, sergei-maertens commented on CHANGELOG.rst
> +* [:backend:`4907`] Improved developer installation documentation.
Move this to "Project maintenance"

2025-01-08 10:33 UTC, sergei-maertens commented on CHANGELOG.rst
> +  request.
```suggestion
* [:backend:`4895`] Added metadata to the outgoing confirmation and cosign request emails.
```

2025-01-08 10:33 UTC, sergei-maertens commented on CHANGELOG.rst
> +* [:backend:`4859`] Improved form state handling.
```suggestion
```
part of the larger objects api prefill feature, can be left out

2025-01-08 10:33 UTC, sergei-maertens commented on CHANGELOG.rst
> +  Open Zaak and Objecten.
```suggestion
* [:backend:`4789`, :backend:`4788`] Added `django-setup-configuration` to programmatically configure Open Forms' 
  connection details to the Objects and ZGW APIs.
```

2025-01-08 10:33 UTC, sergei-maertens commented on CHANGELOG.rst
> +  :ref:`installation_configuration_cli`.
I would merge this with the entry above

2025-01-08 10:33 UTC, sergei-maertens commented on CHANGELOG.rst
> +* Updated documentation concerning frontend toolchains and formio search strategies.
Move to "Project maintenance"

2025-01-08 10:33 UTC, sergei-maertens commented on CHANGELOG.rst
> +  (i.e. on the same day).
```suggestion
* [:backend:`4815`] The minimum submission removal limit is now 0 days, allowing submissions to be deleted on the
   same day they were created.
```

2025-01-08 11:38 UTC, vaszig commented on CHANGELOG.rst
> +  (i.e. on the same day).
This was copied over from the alpha version. Should I change it?

https://github.com/open-formulieren/open-forms/blob/master/CHANGELOG.rst?plain=1#L47

2025-01-08 11:53 UTC, sergei-maertens commented on CHANGELOG.rst
> +  (i.e. on the same day).
Yeah :)

2025-01-09 11:59 UTC, sergei-maertens approved these changes

2025-01-09 12:18 UTC, merged

2025-01-09 12:52 UTC, joeribekker reviewed
Approved.