[#315] Added support for partial dates in StUF ZDS backend and apply to 'geboortedatum'
open-formulieren/open-forms pull request #500
Opened 2021-07-19 13:28 UTC by Bartvaderkin

2021-07-19 13:32 UTC, joeribekker approved these changes

2021-07-19 13:37 UTC, joeribekker requested changes
Je moet ook om kunnen gaan met:

2020-00-00 (of 2020-0-0, of 0-0-0)

De 0 moet als None geinterpreteerd worden.

2021-07-21 14:05 UTC, sergei-maertens approved these changes

2021-07-21 14:06 UTC, sergei-maertens commented
@joeribekker leaving this one for you since you requested changes

2021-07-21 16:58 UTC, joeribekker approved these changes

2021-07-21 16:58 UTC, merged