[WIP] Api error formatting
open-formulieren/open-forms pull request #523
Opened 2021-07-26 10:16 UTC by shea-maykinmedia

Fixes #168

2021-07-28 09:29 UTC, sergei-maertens requested changes

2021-07-28 09:29 UTC, sergei-maertens commented on src/openforms/exception_handler/exceptions.py
> +    default_code = "precondition_failed"
This belongs in `openforms.api.exceptions` to follow the DRF schema (`rest_framework.exceptions`)

2021-07-28 09:29 UTC, sergei-maertens commented on src/openforms/exception_handler/serializers.py
> +    """
```suggestion
    """
    Validation error format, following the NL API Strategy.
    
    See https://docs.geostandaarden.nl/api/API-Strategie/ and 
    https://docs.geostandaarden.nl/api/API-Strategie-ext/#error-handling-0
    """
```

2021-07-28 09:29 UTC, sergei-maertens commented on src/openforms/exception_handler/serializers.py
> +    """
```suggestion
    """
    Error format for HTTP 4xx and 5xx errors.
    
    See https://docs.geostandaarden.nl/api/API-Strategie-ext/#error-handling-0 for the NL API strategy guidelines.
    """
```

2021-07-28 09:29 UTC, sergei-maertens commented on src/openforms/exception_handler/serializers.py
> +    # not according to DSO, but possible for programmatic checking
```suggestion
```

2021-07-28 09:29 UTC, sergei-maertens commented on src/openforms/exception_handler/serializers.py
> +    )
Use translatable `help_text` messages, in English.

2021-07-28 09:29 UTC, sergei-maertens commented on src/openforms/exception_handler/urls.py
> +]
Please put all of the code in this package/app into the `openforms.api` package.

The URL route can be included directly from `openforms.urls` so we don't get the `/api` prefix for the human-facing views.

2021-07-28 09:29 UTC, sergei-maertens commented on src/openforms/exception_handler/utils.py
> +RE_UNDERSCORE = re.compile(r"[a-z]_[a-z]")
Use `djangorestframework_camel_case.util.camelize_re` instead.

2021-07-28 09:29 UTC, sergei-maertens commented on src/openforms/forms/tests/test_api.py
> +                "title": "Invalid input.",
These should also be marked as translatable and go through the translation machinery.

2021-07-28 15:35 UTC, sergei-maertens requested changes

2021-07-28 15:35 UTC, sergei-maertens commented on src/openforms/api/tests/error_views.py
> +    exception = exceptions.APIException("Everything broke")
Please ensure these strings are marked translatable too.

2021-07-28 15:35 UTC, sergei-maertens commented on src/openforms/api/tests/test_error_format.py
> +                "title": "Authenticatiegegevens zijn niet opgegeven.",
Please ensure _every_ test uses translatable strings _everywhere_ for the user-facing messages. I'm not going to copy paste the same comment for every individual test.

2021-07-28 15:35 UTC, sergei-maertens commented on src/openforms/api/views.py
> +        return context
Please move this to `openforms.utils.views` - mixing regular django views and DRF views is confusing.

2021-07-28 15:35 UTC, sergei-maertens commented on src/openforms/conf/base.py
> +    "EXCEPTION_HANDLER": "openforms.api.views.handler",
`handler` really says nothing - and you should really follow the upstream pattern. We're overriding the default DRF exception handler: https://github.com/encode/django-rest-framework/blob/master/rest_framework/views.py#L71

Please use the same function name.

2021-07-29 07:59 UTC, shea-maykinmedia commented
I double checked all the files I believe I marked all the necessary strings as translatable so hopefully I didn't miss any :)

2021-07-29 08:47 UTC, sergei-maertens approved these changes

2021-07-29 08:47 UTC, merged