Add Bag configuration documentation
open-formulieren/open-forms pull request #525
Opened 2021-07-26 14:39 UTC by shea-maykinmedia

There wasn't a related ticket for this though I can create one if we want.

I added some documentation about the `BAG configuration` to the `docs` folder so it'll be shown in read-the-docs.

**Screenshot**

![Screenshot 2021-07-26 at 16 38 01](https://user-images.githubusercontent.com/60747362/127007704-5e164f54-27b8-4486-afa3-4f0105481b3f.png)

2021-07-26 15:01 UTC, shea-maykinmedia commented
The build is failing because an example url gives a 400 response.  If this is otherwise good I'll fix just this but for now I'm going to wait to see if there are other changes that should be made and if there are I'll make the url change as part of the other changes.

2021-07-28 08:09 UTC, sergei-maertens requested changes

2021-07-28 08:09 UTC, sergei-maertens commented on docs/installation/configurations.rst
> +Various configurations can be configured within Open Forms to add data and validation to the forms.
```suggestion
The various modules and plugins in Open Forms require some configuration before they can be used.
```

2021-07-28 08:09 UTC, sergei-maertens commented on docs/installation/configurations.rst
> +-----------------
Please stick to the same type of heading markers as used in the rest of the documentation.

```suggestion
BAG configuration
=================
```

2021-07-28 08:09 UTC, sergei-maertens commented on docs/installation/configurations.rst
> +* ``Label``: What you want to call the service.  Eg. ``Bag Service``
```suggestion
* ``Label``: What you want to call the service.  Eg. ``BAG (Kadaster)``
```

2021-07-28 08:09 UTC, sergei-maertens commented on docs/installation/configurations.rst
> +* ``Type``: The type of service this service is.  Currently it is limited to ``ORC (Overige)``
```suggestion
* ``Type``: The type of API.  Currently it is limited to ``ORC (Overige)``
```

2021-07-28 08:09 UTC, sergei-maertens commented on docs/installation/configurations.rst
> +* ``Header key``: The header key the Api will use to read the Api key.  Will likely be ``X-Api-Key``
```suggestion
* ``Header key``: The HTTP header name to use for the API-key authorization. Will likely be ``X-Api-Key``.
```

2021-07-28 08:09 UTC, sergei-maertens commented on docs/installation/configurations.rst
> +* ``OAS``: A url where the OpenAPI 3 yaml file can be retrieved.  An example file would be https://raw.githubusercontent.com/lvbag/BAG-API/master/Technische%20specificatie/Yaml's/BAG%20API%20Individu
Please also pin the API spec to a git tag or commit rather than the master branch.

2021-07-28 08:09 UTC, sergei-maertens commented on docs/installation/index.rst
> +   configurations
```suggestion
   configuration
```

2021-07-28 08:11 UTC, sergei-maertens commented
> The build is failing because an example url gives a 400 response. If this is otherwise good I'll fix just this but for now I'm going to wait to see if there are other changes that should be made and if there are I'll make the url change as part of the other changes.

The link checks config (in `docs/conf.py`) allows for URL patterns to be excluded, but often if the link does not necessarily have to be clickable in the docs, you should just put it between code back-ticks to format it as code rather than a link.

2021-07-28 10:30 UTC, sergei-maertens approved these changes

2021-07-28 10:30 UTC, merged