Added multidomain switcher
open-formulieren/open-forms pull request #560
Opened 2021-08-13 10:59 UTC by joeribekker

Fixes #325 

This softly depends on https://github.com/maykinmedia/mozilla-django-oidc-db/pull/14

2021-08-13 14:20 UTC, sergei-maertens requested changes
Minor things - I would advise to test out a dev build and then publish the OICD changes to PyPI and only then merge this PR.

2021-08-13 14:20 UTC, sergei-maertens commented on requirements/base.in
> +-e git+https://github.com/maykinmedia/mozilla-django-oidc-db.git@806ba7a0448ecaae0c1271b4afa2f282601e8a6a#egg=mozilla-django-oidc-db
```suggestion
# replace with new PyPI version once https://github.com/maykinmedia/mozilla-django-oidc-db/pull/14 is merged and released
git+https://github.com/maykinmedia/mozilla-django-oidc-db.git@806ba7a0448ecaae0c1271b4afa2f282601e8a6a#egg=mozilla-django-oidc-db
```

This also solves the problem of the package being put in the `src` directory and breaking the isort checks

2021-08-13 14:20 UTC, sergei-maertens commented on src/openforms/multidomain/templates/multidomain/includes/switcher.html
> +        <select onchange="window.location.href=this.value" title="Domain switcher">
```suggestion
        <select onchange="window.location.href=this.value" title="{% trans 'Domain switcher' %}">
```

2021-08-13 14:34 UTC, joeribekker commented
> Minor things - I would advise to test out a dev build and then publish the OICD changes to PyPI and only then merge this PR.

Doing just that atm.

2021-08-16 11:08 UTC, sergei-maertens approved these changes

2021-08-16 11:08 UTC, merged