:recycle: Refs #597 - Handle new format coming from SDK
open-formulieren/open-forms pull request #645
Opened 2021-09-09 13:25 UTC by shea-maykinmedia

Changes needed for points
- Should have human readable values in summary page. Will need a way to save these human readable values after they have been selected.
- On the overview page, the appointment details are rendered weirdly
of #597 

The cause of the displaying of Products and Locations is that we were only saving the id and not the name/human readable value so we could only display the id back at a later point.  Now both will be stored with a dash between the id and name.

One additional positive of this is that in the submission data you will now see both the id and name instead of just the id.

2021-09-09 15:30 UTC, sergei-maertens requested changes
Can we not get a rich object from the SDK or just an ID from the SDK instead of having to parse strings? That looks so fragile, the moment the external appointments service have dashes in their IDs this collapses on itself.

2021-09-10 07:55 UTC, shea-maykinmedia commented
Just an ID is what was being done before but then we don't know the name of the product to display later in the Summary page.  I _think_ an object should work so I'll look into this.

2021-09-13 12:38 UTC, sergei-maertens requested changes
Why aren't tests failing when some tests use the ID-NAME format and others use the object approach?

2021-09-13 12:38 UTC, sergei-maertens commented on src/openforms/appointments/tests/test_utils.py
> +            data={"product": "79-Paspoort", "time": "2021-08-25T17:00:00"},
Wrong format?

2021-09-13 12:38 UTC, sergei-maertens commented on src/openforms/appointments/tests/test_utils.py
> +                "Information not filled in by user: clientDateOfBirth. ",
_all_ user-facing strings must be marked translatable

2021-09-13 12:38 UTC, sergei-maertens commented on src/openforms/submissions/tests/test_models.py
> +                "product": "79-Paspoort",
old format?

2021-09-14 09:03 UTC, shea-maykinmedia commented on src/openforms/appointments/tests/test_utils.py
> +            data={"product": "79-Paspoort", "time": "2021-08-25T17:00:00"},
Yes

2021-09-14 09:03 UTC, shea-maykinmedia commented on src/openforms/submissions/tests/test_models.py
> +                "product": "79-Paspoort",
Yes

2021-09-14 09:31 UTC, shea-maykinmedia commented
The tests that were using the old ID-NAME format but still passing are testing that the data being submitted in the form step is being returned in the correct key when calling the function to get the appointment related data.  So they are checking that the expected data is there but not what the expected data format should be.  Or they were testing the error flows of booking an appointment and so the data that was in the submission step didn't really matter, just that some data was there.

The tests that were testing the code around actually booking the appointment were previously updated to use the correct object format.

2021-09-15 13:59 UTC, sergei-maertens commented
I'll rebase and fix the merge conflicts after #664 is merged, as that one has touched the `AppointmentInfo` part.

2021-09-17 09:14 UTC, sergei-maertens approved these changes

2021-09-17 09:14 UTC, merged