[#607] Added .internal_name field to Form and FormDefinition
open-formulieren/open-forms pull request #679
Opened 2021-09-16 15:46 UTC by Bartvaderkin

2021-09-17 15:31 UTC, sergei-maertens requested changes
Minor remark about the slugify functionality, rest is ok

2021-09-17 15:31 UTC, sergei-maertens commented on src/openforms/js/components/admin/form_design/FormMetaFields.js
> +                    <TextInput value={internalName} onChange={onChange} onBlur={setFormSlug} />
```suggestion
                    <TextInput value={internalName} onChange={onChange} />
```
Slug should be generated from public name, as it's used in URLs

2021-09-17 15:31 UTC, sergei-maertens commented on src/openforms/js/components/admin/form_design/FormStepDefinition.js
> +                        <TextInput value={internalName} onChange={onFieldChange} onBlur={setSlug} />
```suggestion
                        <TextInput value={internalName} onChange={onFieldChange} />
```
Slug should be set based on public name

2021-09-20 08:07 UTC, Bartvaderkin commented
Ugh, copy paste mistake. Should be fixed now.

2021-09-20 08:10 UTC, sergei-maertens approved these changes

2021-09-20 09:11 UTC, merged