Added plugin config tests
open-formulieren/open-forms pull request #955
Opened 2021-11-18 09:03 UTC by joeribekker

Fixes #941

2021-11-29 19:21 UTC, sergei-maertens commented
Before this PR gets too large - can be please get the core/base functionality merged and then implement the individual plugin checks in different PRs?

2021-12-02 09:37 UTC, Bartvaderkin commented
Let's review & merge this first.

2021-12-02 14:30 UTC, sergei-maertens requested changes

2021-12-02 14:30 UTC, sergei-maertens commented on src/openforms/fixtures/default_admin_index.json
> +            "handige-links"
better to move this to the configuration tab - this app group is meant for external URLs for meta-stuff, not for internal Open Forms instance things.

2021-12-02 14:30 UTC, sergei-maertens commented on src/openforms/registrations/contrib/email/plugin.py
> +from openforms.plugins.exceptions import InvalidPluginConfiguration
unused import?

2021-12-02 14:30 UTC, sergei-maertens commented on src/openforms/registrations/contrib/zgw_apis/checks.py
> +    for service_field, api_name, api_operation in services:
```suggestion
    for service_field, api_name, api_resource in services:
```
because `operation = resource + verb`

2021-12-02 14:30 UTC, sergei-maertens commented on src/openforms/urls.py
> +        decorator_include(login_required, "openforms.config.urls", namespace="config"),
that should be at least `staff_required` instead of `login_required`, and please add some access-control tests for this view :)

2021-12-02 16:54 UTC, sergei-maertens commented on src/openforms/emails/tests/test_check_email.py
> +        with patch.multiple(
today I learned `patch.multiple`!

2021-12-02 16:55 UTC, sergei-maertens approved these changes

2021-12-02 16:57 UTC, merged